/*
Copyright 2026 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package importer imports managed resource kinds from
// crossplane-contrib/provider-aws: their generator config, custom types and
// hand-written controller code. Code that cannot be ported mechanically is
// kept behind the importtodo build tag and listed in a report.
package importer

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"

	"golang.org/x/mod/modfile"

	"github.com/teeverr/provider-aws-v2/codegen/internal/generator"
)

// SourceModule is the Go module of crossplane-contrib/provider-aws.
const SourceModule = "github.com/crossplane-contrib/provider-aws"

// Options of an import.
type Options struct {
	// Source is the root of a provider-aws checkout.
	Source string
	// Kinds to import, e.g. DBInstance.
	Kinds []string
	// Generator options; Service and OutputDir are required.
	generator.Options
}

// Run imports o.Kinds of o.Service.
func Run(ctx context.Context, o Options) (*Report, error) {
	svc := strings.ToLower(o.Service)
	o.Service = svc
	r := &Report{Service: svc}

	srcCfg := filepath.Join(o.Source, "apis", svc, "generator-config.yaml")
	if _, err := os.Stat(srcCfg); err != nil {
		return nil, fmt.Errorf("source has no generator config for %s: %w", svc, err)
	}
	if err := generator.ResolveServiceModule(&o.Options); err != nil {
		return nil, err
	}

	lo := o.Options
	lo.GeneratorConfig = srcCfg
	all, err := generator.ListKinds(ctx, lo)
	if err != nil {
		return nil, err
	}
	for _, k := range o.Kinds {
		if !slices.Contains(all, k) {
			return nil, fmt.Errorf("kind %s is not generated by %s (kinds: %s)", k, srcCfg, strings.Join(all, ", "))
		}
	}

	m, err := readManifest(o.OutputDir, svc)
	if err != nil {
		return nil, err
	}
	m.Source = SourceModule
	m.APIVersion = o.APIVersion
	for _, k := range o.Kinds {
		if !slices.Contains(m.Kinds, k) {
			m.Kinds = append(m.Kinds, k)
		}
	}
	o.GeneratorConfig = filepath.Join(o.OutputDir, "apis", svc, "generator-config.yaml")
	if err := writeGeneratorConfig(srcCfg, o.GeneratorConfig, all, m); err != nil {
		return nil, err
	}
	if err := writeManifest(o.OutputDir, svc, m); err != nil {
		return nil, err
	}
	if err := generator.Run(ctx, o.Options); err != nil {
		return nil, fmt.Errorf("cannot generate %s: %w", svc, err)
	}
	r.Kinds = m.Kinds

	tgt, err := loadTarget(o.OutputDir)
	if err != nil {
		return nil, err
	}
	rw := newRewriter(tgt.module, tgt.apiAvailable)
	svcVer := svc + "/" + o.APIVersion
	src, err := parseAPIPackage(filepath.Join(o.Source, "apis", svc, o.APIVersion), SourceModule+"/apis/"+svcVer)
	if err != nil {
		return nil, fmt.Errorf("cannot parse source API package: %w", err)
	}
	ct := &customTypes{src: src, svcVer: svcVer, kinds: o.Kinds, srcKinds: all, tgt: tgt, rw: rw, report: r}
	if err := ct.run(); err != nil {
		return nil, fmt.Errorf("cannot import custom types: %w", err)
	}

	// deepcopy and managed resource methods of the new types
	if err := goGenerate(ctx, filepath.Join(tgt.root, "apis")); err != nil {
		return nil, err
	}
	if err := ct.writeOther(); err != nil {
		return nil, err
	}
	if rw.sdk[svc], err = loadSDKNames(o.OutputDir, svc); err != nil {
		return nil, err
	}
	im := &importer{ctx: ctx, o: o, src: o.Source, tgt: tgt, rw: rw, report: r, newDirs: map[string]bool{}, todo: map[string]int{}}
	for _, k := range o.Kinds {
		lower := strings.ToLower(k)
		srcDir := filepath.Join(o.Source, "pkg", "controller", svc, lower)
		if _, err := os.Stat(srcDir); err != nil {
			r.Add(topicController, "%s: no controller in the source (%s)", k, srcDir)
			continue
		}
		rel := filepath.Join("internal", "controller", svc, lower)
		if err := im.portPackage(srcDir, filepath.Join(tgt.root, rel), tgt.module+"/"+filepath.ToSlash(rel), k); err != nil {
			return nil, fmt.Errorf("cannot port controller of %s: %w", k, err)
		}
	}
	if err := im.portHelpers(); err != nil {
		return nil, fmt.Errorf("cannot port helper packages: %w", err)
	}
	if err := im.typecheck(); err != nil {
		return nil, fmt.Errorf("cannot type check ported code: %w", err)
	}
	return r, nil
}

func goGenerate(ctx context.Context, dir string) error {
	cmd := exec.CommandContext(ctx, "go", "generate", "-tags", "generate", "./...")
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("go generate in %s failed: %w\n%s", dir, err, out)
	}
	return nil
}

// loadTarget reads the module path and the import manifests of the target.
func loadTarget(root string) (*target, error) {
	root, err := filepath.Abs(root)
	if err != nil {
		return nil, err
	}
	gm, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		return nil, err
	}
	t := &target{root: root, module: modfile.ModulePath(gm), kinds: map[string]map[string]bool{}}
	dirs, err := filepath.Glob(filepath.Join(root, "apis", "*", "import.yaml"))
	if err != nil {
		return nil, err
	}
	for _, d := range dirs {
		svc := filepath.Base(filepath.Dir(d))
		m, err := readManifest(root, svc)
		if err != nil {
			return nil, err
		}
		v := m.APIVersion
		if v == "" {
			v = "v1alpha1"
		}
		ks := map[string]bool{}
		for _, k := range m.Kinds {
			ks[k] = true
		}
		t.kinds[svc+"/"+v] = ks
	}
	return t, nil
}
