/*
Copyright 2026 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package importer

import (
	"fmt"
	"sort"
	"strings"
)

// Report lists what an import did and what is left to port by hand.
type Report struct {
	Service string
	Kinds   []string
	// Items are findings, grouped by file or topic.
	Items map[string][]string
}

// Add records a finding about a file or topic.
func (r *Report) Add(topic, format string, args ...any) {
	if r.Items == nil {
		r.Items = map[string][]string{}
	}
	r.Items[topic] = append(r.Items[topic], fmt.Sprintf(format, args...))
}

// Markdown renders the report.
func (r *Report) Markdown() string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Import report: %s (%s)\n\n", r.Service, strings.Join(r.Kinds, ", "))
	b.WriteString("Generated by codegen/cmd/import. Files tagged `//go:build importtodo` are excluded from the build until ported.\n")
	topics := make([]string, 0, len(r.Items))
	for t := range r.Items {
		topics = append(topics, t)
	}
	sort.Strings(topics)
	for _, t := range topics {
		fmt.Fprintf(&b, "\n## %s\n\n", t)
		for _, i := range r.Items[t] {
			fmt.Fprintf(&b, "- %s\n", i)
		}
	}
	return b.String()
}
