// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this DBInstance.
func (mg *DBInstance) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CustomDBInstanceParameters.SourceDBInstanceID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.CustomDBInstanceParameters.SourceDBInstanceIDRef,
		Selector:     mg.Spec.ForProvider.CustomDBInstanceParameters.SourceDBInstanceIDSelector,
		To: reference.To{
			List:    &DBInstanceList{},
			Managed: &DBInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.CustomDBInstanceParameters.SourceDBInstanceID")
	}
	mg.Spec.ForProvider.CustomDBInstanceParameters.SourceDBInstanceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CustomDBInstanceParameters.SourceDBInstanceIDRef = rsp.ResolvedReference

	return nil
}
