{{ template "boilerplate" }}

// Code generated by provider-aws-v2 codegen. DO NOT EDIT.

package {{ .CRD.Names.Lower }}
{{ $kind := .CRD.Names.Camel }}
{{- $readOp := "" }}
{{- $readMany := false }}
{{- if .CRD.Ops.ReadOne }}{{ $readOp = .CRD.Ops.ReadOne }}
{{- else if .CRD.Ops.GetAttributes }}{{ $readOp = .CRD.Ops.GetAttributes }}
{{- else if .CRD.Ops.ReadMany }}{{ $readOp = .CRD.Ops.ReadMany }}{{ $readMany = true }}
{{- end }}
import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/{{ .ServicePackageName }}"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/{{ .ServicePackageName }}/types"
	"github.com/crossplane/crossplane-runtime/v2/pkg/controller"
	"github.com/crossplane/crossplane-runtime/v2/pkg/errors"
	"github.com/crossplane/crossplane-runtime/v2/pkg/event"
	"github.com/crossplane/crossplane-runtime/v2/pkg/feature"
	"github.com/crossplane/crossplane-runtime/v2/pkg/meta"
	"github.com/crossplane/crossplane-runtime/v2/pkg/reconciler/managed"
	cpresource "github.com/crossplane/crossplane-runtime/v2/pkg/resource"
	"github.com/crossplane/crossplane-runtime/v2/pkg/statemetrics"
	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
	"github.com/google/go-cmp/cmp"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"

	svcapitypes "{{ .ModulePath }}/apis/{{ .ServicePackageName }}/{{ .APIVersion }}"
	"{{ .ModulePath }}/apis/v1alpha1"
	awsclient "{{ .ModulePath }}/internal/clients/aws"
)

const (
	errCreateConfig = "cannot create AWS config"
	errCreate       = "cannot create {{ $kind }} in AWS"
	errUpdate       = "cannot update {{ $kind }} in AWS"
	errDescribe     = "failed to describe {{ $kind }}"
	errDelete       = "failed to delete {{ $kind }}"
)

// Hand-written code in this package customizes the controller by appending
// to these slices in an init() function.
var (
	// externalOptions set the hooks of the external client.
	externalOptions []option
	// reconcilerOptions are passed to the managed reconciler, e.g.
	// managed.WithInitializers().
	reconcilerOptions []managed.ReconcilerOption
)

// Setup adds a controller that reconciles {{ $kind }}.
func Setup(mgr ctrl.Manager, o controller.Options) error {
	name := managed.ControllerName(svcapitypes.{{ $kind }}GroupKind)

	opts := []managed.ReconcilerOption{
		managed.WithTypedExternalConnector[*svcapitypes.{{ $kind }}](&connector{
			kube:  mgr.GetClient(),
			usage: cpresource.NewProviderConfigUsageTracker(mgr.GetClient(), &v1alpha1.ProviderConfigUsage{}),
			opts:  externalOptions,
		}),
		managed.WithLogger(o.Logger.WithValues("controller", name)),
		managed.WithPollInterval(o.PollInterval),
		managed.WithRecorder(event.NewAPIRecorder(mgr.GetEventRecorderFor(name))),
	}
	if o.Features.Enabled(feature.EnableBetaManagementPolicies) {
		opts = append(opts, managed.WithManagementPolicies())
	}
	if o.Features.Enabled(feature.EnableAlphaChangeLogs) && o.ChangeLogOptions != nil {
		opts = append(opts, managed.WithChangeLogger(o.ChangeLogOptions.ChangeLogger))
	}
	if o.MetricOptions != nil {
		opts = append(opts, managed.WithMetricRecorder(o.MetricOptions.MRMetrics))
		stateMetricsRecorder := statemetrics.NewMRStateRecorder(
			mgr.GetClient(), o.Logger, o.MetricOptions.MRStateMetrics, &svcapitypes.{{ $kind }}List{}, o.MetricOptions.PollStateMetricInterval,
		)
		if err := mgr.Add(stateMetricsRecorder); err != nil {
			return errors.Wrap(err, "cannot register MR state metrics recorder for kind {{ $kind }}")
		}
	}
	opts = append(opts, reconcilerOptions...)

	r := managed.NewReconciler(mgr, cpresource.ManagedKind(svcapitypes.{{ $kind }}GroupVersionKind), opts...)

	return ctrl.NewControllerManagedBy(mgr).
		Named(name).
		WithOptions(o.ForControllerRuntime()).
		WithEventFilter(cpresource.DesiredStateChanged()).
		For(&svcapitypes.{{ $kind }}{}).
		Complete(r)
}

// SetupGated adds the {{ $kind }} controller once its CRD is available.
func SetupGated(mgr ctrl.Manager, o controller.Options) error {
	o.Gate.Register(func() {
		if err := Setup(mgr, o); err != nil {
			mgr.GetLogger().Error(err, "unable to setup reconciler", "gvk", svcapitypes.{{ $kind }}GroupVersionKind.String())
		}
	}, svcapitypes.{{ $kind }}GroupVersionKind)
	return nil
}

// Client is the part of the {{ .ServicePackageName }} API used by the {{ $kind }} controller.
type Client interface {
{{- if $readOp }}
	{{ $readOp.ExportedName }}(context.Context, *svcsdk.{{ $readOp.InputRef.Shape.ShapeName }}, ...func(*svcsdk.Options)) (*svcsdk.{{ $readOp.OutputRef.Shape.ShapeName }}, error)
{{- end }}
	{{ .CRD.Ops.Create.ExportedName }}(context.Context, *svcsdk.{{ .CRD.Ops.Create.InputRef.Shape.ShapeName }}, ...func(*svcsdk.Options)) (*svcsdk.{{ .CRD.Ops.Create.OutputRef.Shape.ShapeName }}, error)
{{- if .CRD.Ops.Update }}
	{{ .CRD.Ops.Update.ExportedName }}(context.Context, *svcsdk.{{ .CRD.Ops.Update.InputRef.Shape.ShapeName }}, ...func(*svcsdk.Options)) (*svcsdk.{{ .CRD.Ops.Update.OutputRef.Shape.ShapeName }}, error)
{{- end }}
{{- if .CRD.Ops.Delete }}
	{{ .CRD.Ops.Delete.ExportedName }}(context.Context, *svcsdk.{{ .CRD.Ops.Delete.InputRef.Shape.ShapeName }}, ...func(*svcsdk.Options)) (*svcsdk.{{ .CRD.Ops.Delete.OutputRef.Shape.ShapeName }}, error)
{{- end }}
}

type connector struct {
	kube  client.Client
	usage awsclient.Tracker
	opts  []option
}

func (c *connector) Connect(ctx context.Context, cr *svcapitypes.{{ $kind }}) (managed.TypedExternalClient[*svcapitypes.{{ $kind }}], error) {
{{- if IsGlobalService .APIGroup }}
	cfg, err := awsclient.GetConfig(ctx, c.kube, c.usage, cr, awsclient.GlobalRegion)
{{- else }}
	cfg, err := awsclient.GetConfig(ctx, c.kube, c.usage, cr, cr.Spec.ForProvider.Region)
{{- end }}
	if err != nil {
		return nil, errors.Wrap(err, errCreateConfig)
	}
	return newExternal(c.kube, svcsdk.NewFromConfig(cfg), c.opts), nil
}

func (e *external) Observe(ctx context.Context, cr *svcapitypes.{{ $kind }}) (managed.ExternalObservation, error) {
{{- if $readOp }}
	if meta.GetExternalName(cr) == "" {
		return managed.ExternalObservation{ResourceExists: false}, nil
	}
	input, err := Generate{{ $readOp.InputRef.Shape.ShapeName }}(cr)
	if err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "cannot build request")
	}
	if err := e.preObserve(ctx, cr, input); err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "pre-observe failed")
	}
	resp, err := e.client.{{ $readOp.ExportedName }}(ctx, input)
	if err != nil {
		return managed.ExternalObservation{ResourceExists: false}, awsclient.Wrap(cpresource.Ignore(IsNotFound, err), errDescribe)
	}
{{- if $readMany }}
	resp = e.filterList(cr, resp)
	if len(resp.{{ ListMemberNameInReadManyOutput .CRD }}) == 0 {
		return managed.ExternalObservation{ResourceExists: false}, nil
	}
{{- end }}
	currentSpec := cr.Spec.ForProvider.DeepCopy()
	if err := e.lateInitialize(&cr.Spec.ForProvider, resp); err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "late-init failed")
	}
	Generate{{ $kind }}(resp).Status.AtProvider.DeepCopyInto(&cr.Status.AtProvider)
	upToDate := true
	diff := ""
	if !meta.WasDeleted(cr) { // There is no need to run isUpToDate if the resource is deleted
		upToDate, diff, err = e.isUpToDate(ctx, cr, resp)
		if err != nil {
			return managed.ExternalObservation{}, errors.Wrap(err, "isUpToDate check failed")
		}
	}
	return e.postObserve(ctx, cr, resp, managed.ExternalObservation{
		ResourceExists:          true,
		ResourceUpToDate:        upToDate,
		Diff:                    diff,
		ResourceLateInitialized: !cmp.Equal(&cr.Spec.ForProvider, currentSpec),
	}, nil)
{{- else }}
	return e.observe(ctx, cr)
{{- end }}
}

func (e *external) Create(ctx context.Context, cr *svcapitypes.{{ $kind }}) (managed.ExternalCreation, error) {
	cr.Status.SetConditions(xpv2.Creating())
	input, err := Generate{{ .CRD.Ops.Create.InputRef.Shape.ShapeName }}(cr)
	if err != nil {
		return managed.ExternalCreation{}, errors.Wrap(err, "cannot build request")
	}
	if err := e.preCreate(ctx, cr, input); err != nil {
		return managed.ExternalCreation{}, errors.Wrap(err, "pre-create failed")
	}
	resp, err := e.client.{{ .CRD.Ops.Create.ExportedName }}(ctx, input)
	if err != nil {
		return managed.ExternalCreation{}, awsclient.Wrap(err, errCreate)
	}
{{ GoCodeSetCreateOutput .CRD "resp" "cr" 1 }}
	return e.postCreate(ctx, cr, resp, managed.ExternalCreation{}, err)
}

func (e *external) Update(ctx context.Context, cr *svcapitypes.{{ $kind }}) (managed.ExternalUpdate, error) {
{{- if .CRD.Ops.Update }}
	input, err := Generate{{ .CRD.Ops.Update.InputRef.Shape.ShapeName }}(cr)
	if err != nil {
		return managed.ExternalUpdate{}, errors.Wrap(err, "cannot build request")
	}
	if err := e.preUpdate(ctx, cr, input); err != nil {
		return managed.ExternalUpdate{}, errors.Wrap(err, "pre-update failed")
	}
	resp, err := e.client.{{ .CRD.Ops.Update.ExportedName }}(ctx, input)
	return e.postUpdate(ctx, cr, resp, managed.ExternalUpdate{}, awsclient.Wrap(err, errUpdate))
{{- else }}
	return e.update(ctx, cr)
{{- end }}
}

func (e *external) Delete(ctx context.Context, cr *svcapitypes.{{ $kind }}) (managed.ExternalDelete, error) {
	cr.Status.SetConditions(xpv2.Deleting())
{{- if .CRD.Ops.Delete }}
	input, err := Generate{{ .CRD.Ops.Delete.InputRef.Shape.ShapeName }}(cr)
	if err != nil {
		return managed.ExternalDelete{}, errors.Wrap(err, "cannot build request")
	}
	ignore, err := e.preDelete(ctx, cr, input)
	if err != nil {
		return managed.ExternalDelete{}, errors.Wrap(err, "pre-delete failed")
	}
	if ignore {
		return managed.ExternalDelete{}, nil
	}
	resp, err := e.client.{{ .CRD.Ops.Delete.ExportedName }}(ctx, input)
	return e.postDelete(ctx, cr, resp, awsclient.Wrap(cpresource.Ignore(IsNotFound, err), errDelete))
{{- else }}
	return e.delete(ctx, cr)
{{- end }}
}

func (e *external) Disconnect(_ context.Context) error {
	return nil
}

// An option sets hooks of the external client.
type option func(*external)

func newExternal(kube client.Client, client Client, opts []option) *external {
	e := &external{
		kube:   kube,
		client: client,
{{- if $readOp }}
		preObserve:     nopPreObserve,
		postObserve:    nopPostObserve,
		lateInitialize: nopLateInitialize,
		isUpToDate:     alwaysUpToDate,
{{- if $readMany }}
		filterList: nopFilterList,
{{- end }}
{{- else }}
		observe: nopObserve,
{{- end }}
		preCreate:  nopPreCreate,
		postCreate: nopPostCreate,
{{- if .CRD.Ops.Delete }}
		preDelete:  nopPreDelete,
		postDelete: nopPostDelete,
{{- else }}
		delete: nopDelete,
{{- end }}
{{- if .CRD.Ops.Update }}
		preUpdate:  nopPreUpdate,
		postUpdate: nopPostUpdate,
{{- else }}
		update: nopUpdate,
{{- end }}
	}
	for _, f := range opts {
		f(e)
	}
	return e
}

type external struct {
	kube   client.Client
	client Client
{{- if $readOp }}
	preObserve     func(context.Context, *svcapitypes.{{ $kind }}, *svcsdk.{{ $readOp.InputRef.Shape.ShapeName }}) error
	postObserve    func(context.Context, *svcapitypes.{{ $kind }}, *svcsdk.{{ $readOp.OutputRef.Shape.ShapeName }}, managed.ExternalObservation, error) (managed.ExternalObservation, error)
	lateInitialize func(*svcapitypes.{{ $kind }}Parameters, *svcsdk.{{ $readOp.OutputRef.Shape.ShapeName }}) error
	isUpToDate     func(context.Context, *svcapitypes.{{ $kind }}, *svcsdk.{{ $readOp.OutputRef.Shape.ShapeName }}) (bool, string, error)
{{- if $readMany }}
	filterList func(*svcapitypes.{{ $kind }}, *svcsdk.{{ $readOp.OutputRef.Shape.ShapeName }}) *svcsdk.{{ $readOp.OutputRef.Shape.ShapeName }}
{{- end }}
{{- else }}
	observe func(context.Context, *svcapitypes.{{ $kind }}) (managed.ExternalObservation, error)
{{- end }}
	preCreate  func(context.Context, *svcapitypes.{{ $kind }}, *svcsdk.{{ .CRD.Ops.Create.InputRef.Shape.ShapeName }}) error
	postCreate func(context.Context, *svcapitypes.{{ $kind }}, *svcsdk.{{ .CRD.Ops.Create.OutputRef.Shape.ShapeName }}, managed.ExternalCreation, error) (managed.ExternalCreation, error)
{{- if .CRD.Ops.Delete }}
	preDelete  func(context.Context, *svcapitypes.{{ $kind }}, *svcsdk.{{ .CRD.Ops.Delete.InputRef.Shape.ShapeName }}) (bool, error)
	postDelete func(context.Context, *svcapitypes.{{ $kind }}, *svcsdk.{{ .CRD.Ops.Delete.OutputRef.Shape.ShapeName }}, error) (managed.ExternalDelete, error)
{{- else }}
	delete func(context.Context, *svcapitypes.{{ $kind }}) (managed.ExternalDelete, error)
{{- end }}
{{- if .CRD.Ops.Update }}
	preUpdate  func(context.Context, *svcapitypes.{{ $kind }}, *svcsdk.{{ .CRD.Ops.Update.InputRef.Shape.ShapeName }}) error
	postUpdate func(context.Context, *svcapitypes.{{ $kind }}, *svcsdk.{{ .CRD.Ops.Update.OutputRef.Shape.ShapeName }}, managed.ExternalUpdate, error) (managed.ExternalUpdate, error)
{{- else }}
	update func(context.Context, *svcapitypes.{{ $kind }}) (managed.ExternalUpdate, error)
{{- end }}
}
{{ if $readOp }}
func nopPreObserve(context.Context, *svcapitypes.{{ $kind }}, *svcsdk.{{ $readOp.InputRef.Shape.ShapeName }}) error {
	return nil
}

func nopPostObserve(_ context.Context, _ *svcapitypes.{{ $kind }}, _ *svcsdk.{{ $readOp.OutputRef.Shape.ShapeName }}, obs managed.ExternalObservation, err error) (managed.ExternalObservation, error) {
	return obs, err
}

func nopLateInitialize(*svcapitypes.{{ $kind }}Parameters, *svcsdk.{{ $readOp.OutputRef.Shape.ShapeName }}) error {
	return nil
}

func alwaysUpToDate(context.Context, *svcapitypes.{{ $kind }}, *svcsdk.{{ $readOp.OutputRef.Shape.ShapeName }}) (bool, string, error) {
	return true, "", nil
}
{{ if $readMany }}
func nopFilterList(_ *svcapitypes.{{ $kind }}, list *svcsdk.{{ $readOp.OutputRef.Shape.ShapeName }}) *svcsdk.{{ $readOp.OutputRef.Shape.ShapeName }} {
	return list
}
{{ end }}
{{- else }}
func nopObserve(context.Context, *svcapitypes.{{ $kind }}) (managed.ExternalObservation, error) {
	return managed.ExternalObservation{}, nil
}
{{ end }}
func nopPreCreate(context.Context, *svcapitypes.{{ $kind }}, *svcsdk.{{ .CRD.Ops.Create.InputRef.Shape.ShapeName }}) error {
	return nil
}

func nopPostCreate(_ context.Context, _ *svcapitypes.{{ $kind }}, _ *svcsdk.{{ .CRD.Ops.Create.OutputRef.Shape.ShapeName }}, cre managed.ExternalCreation, err error) (managed.ExternalCreation, error) {
	return cre, err
}
{{ if .CRD.Ops.Delete }}
func nopPreDelete(context.Context, *svcapitypes.{{ $kind }}, *svcsdk.{{ .CRD.Ops.Delete.InputRef.Shape.ShapeName }}) (bool, error) {
	return false, nil
}

func nopPostDelete(_ context.Context, _ *svcapitypes.{{ $kind }}, _ *svcsdk.{{ .CRD.Ops.Delete.OutputRef.Shape.ShapeName }}, err error) (managed.ExternalDelete, error) {
	return managed.ExternalDelete{}, err
}
{{ else }}
func nopDelete(context.Context, *svcapitypes.{{ $kind }}) (managed.ExternalDelete, error) {
	return managed.ExternalDelete{}, nil
}
{{ end }}
{{- if .CRD.Ops.Update }}
func nopPreUpdate(context.Context, *svcapitypes.{{ $kind }}, *svcsdk.{{ .CRD.Ops.Update.InputRef.Shape.ShapeName }}) error {
	return nil
}

func nopPostUpdate(_ context.Context, _ *svcapitypes.{{ $kind }}, _ *svcsdk.{{ .CRD.Ops.Update.OutputRef.Shape.ShapeName }}, upd managed.ExternalUpdate, err error) (managed.ExternalUpdate, error) {
	return upd, err
}
{{- else }}
func nopUpdate(context.Context, *svcapitypes.{{ $kind }}) (managed.ExternalUpdate, error) {
	return managed.ExternalUpdate{}, nil
}
{{- end }}
