{{ template "boilerplate" }}

// Code generated by provider-aws-v2 codegen. DO NOT EDIT.

package {{ .CRD.Names.Lower }}

import (
{{- if .CRD.TypeImports }}
{{- range $packagePath := .CRD.SortedTypeImportPaths }}
{{- $alias := (index $.CRD.TypeImports $packagePath) }}
	{{ if $alias }}{{ $alias }} {{ end }}"{{ $packagePath }}"
{{- end }}
{{- end }}
	"errors"

	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/{{ .ServicePackageName }}"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/{{ .ServicePackageName }}/types"
	"github.com/aws/smithy-go"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "{{ .ModulePath }}/apis/{{ .ServicePackageName }}/{{ .APIVersion }}"
)

{{ if .CRD.Ops.ReadOne }}
	{{- template "sdk_find_read_one" . }}
{{- else if .CRD.Ops.GetAttributes }}
	{{- template "sdk_find_get_attributes" . }}
{{- else if .CRD.Ops.ReadMany }}
	{{- template "sdk_find_read_many" . }}
{{- end }}

// Generate{{ .CRD.Ops.Create.InputRef.Shape.ShapeName }} returns a create input.
func Generate{{ .CRD.Ops.Create.InputRef.Shape.ShapeName }}(cr *svcapitypes.{{ .CRD.Names.Camel }}) (*svcsdk.{{ .CRD.Ops.Create.InputRef.Shape.ShapeName }}, error) {
	res := &svcsdk.{{ .CRD.Ops.Create.InputRef.Shape.ShapeName }}{}
{{ GoCodeSetCreateInput .CRD "cr" "res" 1 }}
	return res, nil
}
{{ if .CRD.Ops.Update }}
// Generate{{ .CRD.Ops.Update.InputRef.Shape.ShapeName }} returns an update input.
func Generate{{ .CRD.Ops.Update.InputRef.Shape.ShapeName }}(cr *svcapitypes.{{ .CRD.Names.Camel }}) (*svcsdk.{{ .CRD.Ops.Update.InputRef.Shape.ShapeName }}, error) {
	res := &svcsdk.{{ .CRD.Ops.Update.InputRef.Shape.ShapeName }}{}
{{ GoCodeSetUpdateInput .CRD "cr" "res" 1 }}
	return res, nil
}
{{ end }}
{{- if .CRD.Ops.Delete }}
// Generate{{ .CRD.Ops.Delete.InputRef.Shape.ShapeName }} returns a deletion input.
func Generate{{ .CRD.Ops.Delete.InputRef.Shape.ShapeName }}(cr *svcapitypes.{{ .CRD.Names.Camel }}) (*svcsdk.{{ .CRD.Ops.Delete.InputRef.Shape.ShapeName }}, error) {
	res := &svcsdk.{{ .CRD.Ops.Delete.InputRef.Shape.ShapeName }}{}
{{ GoCodeSetDeleteInput .CRD "cr" "res" 1 }}
	return res, nil
}
{{ end }}
// IsNotFound returns whether the given error means that the resource does not exist.
func IsNotFound(err error) bool {
	var ae smithy.APIError
	return errors.As(err, &ae) && ae.ErrorCode() == "{{ ResourceExceptionCode .CRD 404 }}"
}
