{{ template "boilerplate" }}

// Code generated by provider-aws-v2 codegen. DO NOT EDIT.

// Package {{ .ServicePackageName }} contains the controllers of the {{ .ServicePackageName }} API group.
package {{ .ServicePackageName }}

import (
	"github.com/crossplane/crossplane-runtime/v2/pkg/controller"
	ctrl "sigs.k8s.io/controller-runtime"
{{ range .CRDs }}
	"{{ $.ModulePath }}/internal/controller/{{ $.ServicePackageName }}/{{ .Names.Lower }}"
{{- end }}
)

// SetupGated adds all {{ .ServicePackageName }} controllers to the manager,
// each once its CRD is available.
func SetupGated(mgr ctrl.Manager, o controller.Options) error {
	for _, setup := range []func(ctrl.Manager, controller.Options) error{
{{- range .CRDs }}
		{{ .Names.Lower }}.SetupGated,
{{- end }}
	} {
		if err := setup(mgr, o); err != nil {
			return err
		}
	}
	return nil
}
