/*
Copyright 2026 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const boilerplate = `/*
Copyright 2026 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
`

const generatedHeader = "// Code generated by provider-aws-v2 codegen. DO NOT EDIT.\n"

// WriteRegistries regenerates apis/zz_services.go and
// internal/controller/zz_services.go from the services found on disk, so that
// all generated and imported services are registered in the scheme and the
// controller manager.
func WriteRegistries(root string) error {
	apiPkgs, err := apiPackages(root)
	if err != nil {
		return err
	}
	ctrlPkgs, err := controllerPackages(root)
	if err != nil {
		return err
	}

	var a strings.Builder
	a.WriteString(boilerplate + "\n" + generatedHeader + "\npackage apis\n\nimport (\n")
	for _, p := range apiPkgs {
		fmt.Fprintf(&a, "\t%s %q\n", p.alias, ModulePath+"/apis/"+p.path)
	}
	a.WriteString(")\n")
	if len(apiPkgs) > 0 {
		a.WriteString("\nfunc init() {\n\tAddToSchemes = append(AddToSchemes,\n")
		for _, p := range apiPkgs {
			fmt.Fprintf(&a, "\t\t%s.SchemeBuilder.AddToScheme,\n", p.alias)
		}
		a.WriteString("\t)\n}\n")
	}
	if err := writeGo(filepath.Join(root, "apis", "zz_services.go"), []byte(a.String())); err != nil {
		return err
	}

	var c strings.Builder
	c.WriteString(boilerplate + "\n" + generatedHeader + "\npackage controller\n\nimport (\n")
	c.WriteString("\t\"github.com/crossplane/crossplane-runtime/v2/pkg/controller\"\n\tctrl \"sigs.k8s.io/controller-runtime\"\n\n")
	for _, p := range ctrlPkgs {
		fmt.Fprintf(&c, "\t%q\n", ModulePath+"/internal/controller/"+p)
	}
	c.WriteString(")\n\n// serviceSetups are the SetupGated functions of all services.\nvar serviceSetups = []func(ctrl.Manager, controller.Options) error{\n")
	for _, p := range ctrlPkgs {
		fmt.Fprintf(&c, "\t%s.SetupGated,\n", p)
	}
	c.WriteString("}\n")
	return writeGo(filepath.Join(root, "internal", "controller", "zz_services.go"), []byte(c.String()))
}

type apiPkg struct{ path, alias string }

// apiPackages returns apis/<service>/<version> packages that contain
// generated or imported managed resources.
func apiPackages(root string) ([]apiPkg, error) {
	matches, err := filepath.Glob(filepath.Join(root, "apis", "*", "*", "zz_groupversion_info.go"))
	if err != nil {
		return nil, err
	}
	pkgs := make([]apiPkg, 0, len(matches))
	for _, m := range matches {
		ver := filepath.Base(filepath.Dir(m))
		svc := filepath.Base(filepath.Dir(filepath.Dir(m)))
		pkgs = append(pkgs, apiPkg{path: svc + "/" + ver, alias: svc + ver})
	}
	sort.Slice(pkgs, func(i, j int) bool { return pkgs[i].path < pkgs[j].path })
	return pkgs, nil
}

// controllerPackages returns internal/controller/<service> packages that have
// a zz_setup.go.
func controllerPackages(root string) ([]string, error) {
	matches, err := filepath.Glob(filepath.Join(root, "internal", "controller", "*", "zz_setup.go"))
	if err != nil {
		return nil, err
	}
	pkgs := make([]string, 0, len(matches))
	for _, m := range matches {
		if _, err := os.Stat(m); err == nil {
			pkgs = append(pkgs, filepath.Base(filepath.Dir(m)))
		}
	}
	sort.Strings(pkgs)
	return pkgs, nil
}
