/*
Copyright 2026 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by provider-aws-v2 codegen. DO NOT EDIT.

package dbinstance

import (
	"errors"
	"fmt"
	"math"

	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/rds"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/rds/types"
	"github.com/aws/smithy-go"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/teeverr/provider-aws-v2/apis/rds/v1alpha1"
)

// GenerateDescribeDBInstancesInput returns input for read
// operation.
func GenerateDescribeDBInstancesInput(cr *svcapitypes.DBInstance) (*svcsdk.DescribeDBInstancesInput, error) {
	res := &svcsdk.DescribeDBInstancesInput{}

	if cr.Status.AtProvider.DBInstanceIdentifier != nil {
		res.DBInstanceIdentifier = cr.Status.AtProvider.DBInstanceIdentifier
	}

	return res, nil
}

// GenerateDBInstance returns the current state in the form of *svcapitypes.DBInstance.
func GenerateDBInstance(resp *svcsdk.DescribeDBInstancesOutput) *svcapitypes.DBInstance {
	cr := &svcapitypes.DBInstance{}

	found := false
	for _, elem := range resp.DBInstances {
		if elem.ActivityStreamEngineNativeAuditFieldsIncluded != nil {
			cr.Status.AtProvider.ActivityStreamEngineNativeAuditFieldsIncluded = elem.ActivityStreamEngineNativeAuditFieldsIncluded
		} else {
			cr.Status.AtProvider.ActivityStreamEngineNativeAuditFieldsIncluded = nil
		}
		if elem.ActivityStreamKinesisStreamName != nil {
			cr.Status.AtProvider.ActivityStreamKinesisStreamName = elem.ActivityStreamKinesisStreamName
		} else {
			cr.Status.AtProvider.ActivityStreamKinesisStreamName = nil
		}
		if elem.ActivityStreamKmsKeyId != nil {
			cr.Status.AtProvider.ActivityStreamKMSKeyID = elem.ActivityStreamKmsKeyId
		} else {
			cr.Status.AtProvider.ActivityStreamKMSKeyID = nil
		}
		if elem.ActivityStreamMode != "" {
			cr.Status.AtProvider.ActivityStreamMode = aws.String(string(elem.ActivityStreamMode))
		} else {
			cr.Status.AtProvider.ActivityStreamMode = nil
		}
		if elem.ActivityStreamPolicyStatus != "" {
			cr.Status.AtProvider.ActivityStreamPolicyStatus = aws.String(string(elem.ActivityStreamPolicyStatus))
		} else {
			cr.Status.AtProvider.ActivityStreamPolicyStatus = nil
		}
		if elem.ActivityStreamStatus != "" {
			cr.Status.AtProvider.ActivityStreamStatus = aws.String(string(elem.ActivityStreamStatus))
		} else {
			cr.Status.AtProvider.ActivityStreamStatus = nil
		}
		if elem.AdditionalStorageVolumes != nil {
			f6 := []*svcapitypes.AdditionalStorageVolume{}
			for _, f6iter := range elem.AdditionalStorageVolumes {
				f6elem := &svcapitypes.AdditionalStorageVolume{}
				if f6iter.AllocatedStorage != nil {
					allocatedStorageCopy := int64(*f6iter.AllocatedStorage)
					f6elem.AllocatedStorage = &allocatedStorageCopy
				}
				if f6iter.IOPS != nil {
					iopsCopy := int64(*f6iter.IOPS)
					f6elem.IOPS = &iopsCopy
				}
				if f6iter.MaxAllocatedStorage != nil {
					maxAllocatedStorageCopy := int64(*f6iter.MaxAllocatedStorage)
					f6elem.MaxAllocatedStorage = &maxAllocatedStorageCopy
				}
				if f6iter.StorageThroughput != nil {
					storageThroughputCopy := int64(*f6iter.StorageThroughput)
					f6elem.StorageThroughput = &storageThroughputCopy
				}
				if f6iter.StorageType != nil {
					f6elem.StorageType = f6iter.StorageType
				}
				if f6iter.VolumeName != nil {
					f6elem.VolumeName = f6iter.VolumeName
				}
				f6 = append(f6, f6elem)
			}
			cr.Spec.ForProvider.AdditionalStorageVolumes = f6
		} else {
			cr.Spec.ForProvider.AdditionalStorageVolumes = nil
		}
		if elem.AllocatedStorage != nil {
			allocatedStorageCopy := int64(*elem.AllocatedStorage)
			cr.Spec.ForProvider.AllocatedStorage = &allocatedStorageCopy
		} else {
			cr.Spec.ForProvider.AllocatedStorage = nil
		}
		if elem.AssociatedRoles != nil {
			f8 := []*svcapitypes.DBInstanceRole{}
			for _, f8iter := range elem.AssociatedRoles {
				f8elem := &svcapitypes.DBInstanceRole{}
				if f8iter.FeatureName != nil {
					f8elem.FeatureName = f8iter.FeatureName
				}
				if f8iter.RoleArn != nil {
					f8elem.RoleARN = f8iter.RoleArn
				}
				if f8iter.Status != nil {
					f8elem.Status = f8iter.Status
				}
				f8 = append(f8, f8elem)
			}
			cr.Status.AtProvider.AssociatedRoles = f8
		} else {
			cr.Status.AtProvider.AssociatedRoles = nil
		}
		if elem.AutoMinorVersionUpgrade != nil {
			cr.Spec.ForProvider.AutoMinorVersionUpgrade = elem.AutoMinorVersionUpgrade
		} else {
			cr.Spec.ForProvider.AutoMinorVersionUpgrade = nil
		}
		if elem.AutomaticRestartTime != nil {
			cr.Status.AtProvider.AutomaticRestartTime = &metav1.Time{Time: *elem.AutomaticRestartTime}
		} else {
			cr.Status.AtProvider.AutomaticRestartTime = nil
		}
		if elem.AutomationMode != "" {
			cr.Status.AtProvider.AutomationMode = aws.String(string(elem.AutomationMode))
		} else {
			cr.Status.AtProvider.AutomationMode = nil
		}
		if elem.AvailabilityZone != nil {
			cr.Spec.ForProvider.AvailabilityZone = elem.AvailabilityZone
		} else {
			cr.Spec.ForProvider.AvailabilityZone = nil
		}
		if elem.AwsBackupRecoveryPointArn != nil {
			cr.Status.AtProvider.AWSBackupRecoveryPointARN = elem.AwsBackupRecoveryPointArn
		} else {
			cr.Status.AtProvider.AWSBackupRecoveryPointARN = nil
		}
		if elem.BackupRetentionPeriod != nil {
			backupRetentionPeriodCopy := int64(*elem.BackupRetentionPeriod)
			cr.Spec.ForProvider.BackupRetentionPeriod = &backupRetentionPeriodCopy
		} else {
			cr.Spec.ForProvider.BackupRetentionPeriod = nil
		}
		if elem.BackupTarget != nil {
			cr.Spec.ForProvider.BackupTarget = elem.BackupTarget
		} else {
			cr.Spec.ForProvider.BackupTarget = nil
		}
		if elem.CACertificateIdentifier != nil {
			cr.Spec.ForProvider.CACertificateIdentifier = elem.CACertificateIdentifier
		} else {
			cr.Spec.ForProvider.CACertificateIdentifier = nil
		}
		if elem.CertificateDetails != nil {
			f17 := &svcapitypes.CertificateDetails{}
			if elem.CertificateDetails.CAIdentifier != nil {
				f17.CAIdentifier = elem.CertificateDetails.CAIdentifier
			}
			if elem.CertificateDetails.ValidTill != nil {
				f17.ValidTill = &metav1.Time{Time: *elem.CertificateDetails.ValidTill}
			}
			cr.Status.AtProvider.CertificateDetails = f17
		} else {
			cr.Status.AtProvider.CertificateDetails = nil
		}
		if elem.CharacterSetName != nil {
			cr.Spec.ForProvider.CharacterSetName = elem.CharacterSetName
		} else {
			cr.Spec.ForProvider.CharacterSetName = nil
		}
		if elem.CopyTagsToSnapshot != nil {
			cr.Spec.ForProvider.CopyTagsToSnapshot = elem.CopyTagsToSnapshot
		} else {
			cr.Spec.ForProvider.CopyTagsToSnapshot = nil
		}
		if elem.CustomIamInstanceProfile != nil {
			cr.Spec.ForProvider.CustomIAMInstanceProfile = elem.CustomIamInstanceProfile
		} else {
			cr.Spec.ForProvider.CustomIAMInstanceProfile = nil
		}
		if elem.CustomerOwnedIpEnabled != nil {
			cr.Status.AtProvider.CustomerOwnedIPEnabled = elem.CustomerOwnedIpEnabled
		} else {
			cr.Status.AtProvider.CustomerOwnedIPEnabled = nil
		}
		if elem.DBClusterIdentifier != nil {
			cr.Spec.ForProvider.DBClusterIdentifier = elem.DBClusterIdentifier
		} else {
			cr.Spec.ForProvider.DBClusterIdentifier = nil
		}
		if elem.DBInstanceArn != nil {
			cr.Status.AtProvider.DBInstanceARN = elem.DBInstanceArn
		} else {
			cr.Status.AtProvider.DBInstanceARN = nil
		}
		if elem.DBInstanceAutomatedBackupsReplications != nil {
			f24 := []*svcapitypes.DBInstanceAutomatedBackupsReplication{}
			for _, f24iter := range elem.DBInstanceAutomatedBackupsReplications {
				f24elem := &svcapitypes.DBInstanceAutomatedBackupsReplication{}
				if f24iter.DBInstanceAutomatedBackupsArn != nil {
					f24elem.DBInstanceAutomatedBackupsARN = f24iter.DBInstanceAutomatedBackupsArn
				}
				f24 = append(f24, f24elem)
			}
			cr.Status.AtProvider.DBInstanceAutomatedBackupsReplications = f24
		} else {
			cr.Status.AtProvider.DBInstanceAutomatedBackupsReplications = nil
		}
		if elem.DBInstanceClass != nil {
			cr.Spec.ForProvider.DBInstanceClass = elem.DBInstanceClass
		} else {
			cr.Spec.ForProvider.DBInstanceClass = nil
		}
		if elem.DBInstanceIdentifier != nil {
			cr.Status.AtProvider.DBInstanceIdentifier = elem.DBInstanceIdentifier
		} else {
			cr.Status.AtProvider.DBInstanceIdentifier = nil
		}
		if elem.DBInstanceStatus != nil {
			cr.Status.AtProvider.DBInstanceStatus = elem.DBInstanceStatus
		} else {
			cr.Status.AtProvider.DBInstanceStatus = nil
		}
		if elem.DBName != nil {
			cr.Spec.ForProvider.DBName = elem.DBName
		} else {
			cr.Spec.ForProvider.DBName = nil
		}
		if elem.DBParameterGroups != nil {
			f29 := []*svcapitypes.DBParameterGroupStatus{}
			for _, f29iter := range elem.DBParameterGroups {
				f29elem := &svcapitypes.DBParameterGroupStatus{}
				if f29iter.DBParameterGroupName != nil {
					f29elem.DBParameterGroupName = f29iter.DBParameterGroupName
				}
				if f29iter.ParameterApplyStatus != nil {
					f29elem.ParameterApplyStatus = f29iter.ParameterApplyStatus
				}
				f29 = append(f29, f29elem)
			}
			cr.Status.AtProvider.DBParameterGroups = f29
		} else {
			cr.Status.AtProvider.DBParameterGroups = nil
		}
		if elem.DBSecurityGroups != nil {
			f30 := []*svcapitypes.DBSecurityGroupMembership{}
			for _, f30iter := range elem.DBSecurityGroups {
				f30elem := &svcapitypes.DBSecurityGroupMembership{}
				if f30iter.DBSecurityGroupName != nil {
					f30elem.DBSecurityGroupName = f30iter.DBSecurityGroupName
				}
				if f30iter.Status != nil {
					f30elem.Status = f30iter.Status
				}
				f30 = append(f30, f30elem)
			}
			cr.Status.AtProvider.DBSecurityGroups = f30
		} else {
			cr.Status.AtProvider.DBSecurityGroups = nil
		}
		if elem.DBSubnetGroup != nil {
			f31 := &svcapitypes.DBSubnetGroup{}
			if elem.DBSubnetGroup.DBSubnetGroupArn != nil {
				f31.DBSubnetGroupARN = elem.DBSubnetGroup.DBSubnetGroupArn
			}
			if elem.DBSubnetGroup.DBSubnetGroupDescription != nil {
				f31.DBSubnetGroupDescription = elem.DBSubnetGroup.DBSubnetGroupDescription
			}
			if elem.DBSubnetGroup.DBSubnetGroupName != nil {
				f31.DBSubnetGroupName = elem.DBSubnetGroup.DBSubnetGroupName
			}
			if elem.DBSubnetGroup.SubnetGroupStatus != nil {
				f31.SubnetGroupStatus = elem.DBSubnetGroup.SubnetGroupStatus
			}
			if elem.DBSubnetGroup.Subnets != nil {
				f31f4 := []*svcapitypes.Subnet{}
				for _, f31f4iter := range elem.DBSubnetGroup.Subnets {
					f31f4elem := &svcapitypes.Subnet{}
					if f31f4iter.SubnetAvailabilityZone != nil {
						f31f4elemf0 := &svcapitypes.AvailabilityZone{}
						if f31f4iter.SubnetAvailabilityZone.Name != nil {
							f31f4elemf0.Name = f31f4iter.SubnetAvailabilityZone.Name
						}
						f31f4elem.SubnetAvailabilityZone = f31f4elemf0
					}
					if f31f4iter.SubnetIdentifier != nil {
						f31f4elem.SubnetIdentifier = f31f4iter.SubnetIdentifier
					}
					if f31f4iter.SubnetOutpost != nil {
						f31f4elemf2 := &svcapitypes.Outpost{}
						if f31f4iter.SubnetOutpost.Arn != nil {
							f31f4elemf2.ARN = f31f4iter.SubnetOutpost.Arn
						}
						f31f4elem.SubnetOutpost = f31f4elemf2
					}
					if f31f4iter.SubnetStatus != nil {
						f31f4elem.SubnetStatus = f31f4iter.SubnetStatus
					}
					f31f4 = append(f31f4, f31f4elem)
				}
				f31.Subnets = f31f4
			}
			if elem.DBSubnetGroup.SupportedNetworkTypes != nil {
				f31.SupportedNetworkTypes = aws.StringSlice(elem.DBSubnetGroup.SupportedNetworkTypes)
			}
			if elem.DBSubnetGroup.VpcId != nil {
				f31.VPCID = elem.DBSubnetGroup.VpcId
			}
			cr.Status.AtProvider.DBSubnetGroup = f31
		} else {
			cr.Status.AtProvider.DBSubnetGroup = nil
		}
		if elem.DBSystemId != nil {
			cr.Spec.ForProvider.DBSystemID = elem.DBSystemId
		} else {
			cr.Spec.ForProvider.DBSystemID = nil
		}
		if elem.DatabaseInsightsMode != "" {
			cr.Spec.ForProvider.DatabaseInsightsMode = aws.String(string(elem.DatabaseInsightsMode))
		} else {
			cr.Spec.ForProvider.DatabaseInsightsMode = nil
		}
		if elem.DbInstancePort != nil {
			dbInstancePortCopy := int64(*elem.DbInstancePort)
			cr.Status.AtProvider.DBInstancePort = &dbInstancePortCopy
		} else {
			cr.Status.AtProvider.DBInstancePort = nil
		}
		if elem.DbiResourceId != nil {
			cr.Status.AtProvider.DBIResourceID = elem.DbiResourceId
		} else {
			cr.Status.AtProvider.DBIResourceID = nil
		}
		if elem.DedicatedLogVolume != nil {
			cr.Spec.ForProvider.DedicatedLogVolume = elem.DedicatedLogVolume
		} else {
			cr.Spec.ForProvider.DedicatedLogVolume = nil
		}
		if elem.DeletionProtection != nil {
			cr.Spec.ForProvider.DeletionProtection = elem.DeletionProtection
		} else {
			cr.Spec.ForProvider.DeletionProtection = nil
		}
		if elem.DomainMemberships != nil {
			f38 := []*svcapitypes.DomainMembership{}
			for _, f38iter := range elem.DomainMemberships {
				f38elem := &svcapitypes.DomainMembership{}
				if f38iter.AuthSecretArn != nil {
					f38elem.AuthSecretARN = f38iter.AuthSecretArn
				}
				if f38iter.DnsIps != nil {
					f38elem.DNSIPs = aws.StringSlice(f38iter.DnsIps)
				}
				if f38iter.Domain != nil {
					f38elem.Domain = f38iter.Domain
				}
				if f38iter.FQDN != nil {
					f38elem.FQDN = f38iter.FQDN
				}
				if f38iter.IAMRoleName != nil {
					f38elem.IAMRoleName = f38iter.IAMRoleName
				}
				if f38iter.OU != nil {
					f38elem.OU = f38iter.OU
				}
				if f38iter.Status != nil {
					f38elem.Status = f38iter.Status
				}
				f38 = append(f38, f38elem)
			}
			cr.Status.AtProvider.DomainMemberships = f38
		} else {
			cr.Status.AtProvider.DomainMemberships = nil
		}
		if elem.EnabledCloudwatchLogsExports != nil {
			cr.Status.AtProvider.EnabledCloudwatchLogsExports = aws.StringSlice(elem.EnabledCloudwatchLogsExports)
		} else {
			cr.Status.AtProvider.EnabledCloudwatchLogsExports = nil
		}
		if elem.Endpoint != nil {
			f40 := &svcapitypes.Endpoint{}
			if elem.Endpoint.Address != nil {
				f40.Address = elem.Endpoint.Address
			}
			if elem.Endpoint.HostedZoneId != nil {
				f40.HostedZoneID = elem.Endpoint.HostedZoneId
			}
			if elem.Endpoint.Port != nil {
				portCopy := int64(*elem.Endpoint.Port)
				f40.Port = &portCopy
			}
			cr.Status.AtProvider.Endpoint = f40
		} else {
			cr.Status.AtProvider.Endpoint = nil
		}
		if elem.Engine != nil {
			cr.Spec.ForProvider.Engine = elem.Engine
		} else {
			cr.Spec.ForProvider.Engine = nil
		}
		if elem.EngineLifecycleSupport != nil {
			cr.Spec.ForProvider.EngineLifecycleSupport = elem.EngineLifecycleSupport
		} else {
			cr.Spec.ForProvider.EngineLifecycleSupport = nil
		}
		if elem.EngineVersion != nil {
			cr.Status.AtProvider.EngineVersion = elem.EngineVersion
		} else {
			cr.Status.AtProvider.EngineVersion = nil
		}
		if elem.EnhancedMonitoringResourceArn != nil {
			cr.Status.AtProvider.EnhancedMonitoringResourceARN = elem.EnhancedMonitoringResourceArn
		} else {
			cr.Status.AtProvider.EnhancedMonitoringResourceARN = nil
		}
		if elem.IAMDatabaseAuthenticationEnabled != nil {
			cr.Status.AtProvider.IAMDatabaseAuthenticationEnabled = elem.IAMDatabaseAuthenticationEnabled
		} else {
			cr.Status.AtProvider.IAMDatabaseAuthenticationEnabled = nil
		}
		if elem.InstanceCreateTime != nil {
			cr.Status.AtProvider.InstanceCreateTime = &metav1.Time{Time: *elem.InstanceCreateTime}
		} else {
			cr.Status.AtProvider.InstanceCreateTime = nil
		}
		if elem.Iops != nil {
			iopsCopy := int64(*elem.Iops)
			cr.Spec.ForProvider.IOPS = &iopsCopy
		} else {
			cr.Spec.ForProvider.IOPS = nil
		}
		if elem.IsStorageConfigUpgradeAvailable != nil {
			cr.Status.AtProvider.IsStorageConfigUpgradeAvailable = elem.IsStorageConfigUpgradeAvailable
		} else {
			cr.Status.AtProvider.IsStorageConfigUpgradeAvailable = nil
		}
		if elem.KmsKeyId != nil {
			cr.Spec.ForProvider.KMSKeyID = elem.KmsKeyId
		} else {
			cr.Spec.ForProvider.KMSKeyID = nil
		}
		if elem.LatestRestorableTime != nil {
			cr.Status.AtProvider.LatestRestorableTime = &metav1.Time{Time: *elem.LatestRestorableTime}
		} else {
			cr.Status.AtProvider.LatestRestorableTime = nil
		}
		if elem.LicenseModel != nil {
			cr.Spec.ForProvider.LicenseModel = elem.LicenseModel
		} else {
			cr.Spec.ForProvider.LicenseModel = nil
		}
		if elem.ListenerEndpoint != nil {
			f52 := &svcapitypes.Endpoint{}
			if elem.ListenerEndpoint.Address != nil {
				f52.Address = elem.ListenerEndpoint.Address
			}
			if elem.ListenerEndpoint.HostedZoneId != nil {
				f52.HostedZoneID = elem.ListenerEndpoint.HostedZoneId
			}
			if elem.ListenerEndpoint.Port != nil {
				portCopy := int64(*elem.ListenerEndpoint.Port)
				f52.Port = &portCopy
			}
			cr.Status.AtProvider.ListenerEndpoint = f52
		} else {
			cr.Status.AtProvider.ListenerEndpoint = nil
		}
		if elem.MasterUserSecret != nil {
			f53 := &svcapitypes.MasterUserSecret{}
			if elem.MasterUserSecret.KmsKeyId != nil {
				f53.KMSKeyID = elem.MasterUserSecret.KmsKeyId
			}
			if elem.MasterUserSecret.SecretArn != nil {
				f53.SecretARN = elem.MasterUserSecret.SecretArn
			}
			if elem.MasterUserSecret.SecretStatus != nil {
				f53.SecretStatus = elem.MasterUserSecret.SecretStatus
			}
			cr.Status.AtProvider.MasterUserSecret = f53
		} else {
			cr.Status.AtProvider.MasterUserSecret = nil
		}
		if elem.MasterUsername != nil {
			cr.Spec.ForProvider.MasterUsername = elem.MasterUsername
		} else {
			cr.Spec.ForProvider.MasterUsername = nil
		}
		if elem.MaxAllocatedStorage != nil {
			maxAllocatedStorageCopy := int64(*elem.MaxAllocatedStorage)
			cr.Spec.ForProvider.MaxAllocatedStorage = &maxAllocatedStorageCopy
		} else {
			cr.Spec.ForProvider.MaxAllocatedStorage = nil
		}
		if elem.MonitoringInterval != nil {
			monitoringIntervalCopy := int64(*elem.MonitoringInterval)
			cr.Spec.ForProvider.MonitoringInterval = &monitoringIntervalCopy
		} else {
			cr.Spec.ForProvider.MonitoringInterval = nil
		}
		if elem.MonitoringRoleArn != nil {
			cr.Spec.ForProvider.MonitoringRoleARN = elem.MonitoringRoleArn
		} else {
			cr.Spec.ForProvider.MonitoringRoleARN = nil
		}
		if elem.MultiAZ != nil {
			cr.Spec.ForProvider.MultiAZ = elem.MultiAZ
		} else {
			cr.Spec.ForProvider.MultiAZ = nil
		}
		if elem.MultiTenant != nil {
			cr.Spec.ForProvider.MultiTenant = elem.MultiTenant
		} else {
			cr.Spec.ForProvider.MultiTenant = nil
		}
		if elem.NcharCharacterSetName != nil {
			cr.Spec.ForProvider.NcharCharacterSetName = elem.NcharCharacterSetName
		} else {
			cr.Spec.ForProvider.NcharCharacterSetName = nil
		}
		if elem.NetworkType != nil {
			cr.Spec.ForProvider.NetworkType = elem.NetworkType
		} else {
			cr.Spec.ForProvider.NetworkType = nil
		}
		if elem.OptionGroupMemberships != nil {
			f62 := []*svcapitypes.OptionGroupMembership{}
			for _, f62iter := range elem.OptionGroupMemberships {
				f62elem := &svcapitypes.OptionGroupMembership{}
				if f62iter.OptionGroupName != nil {
					f62elem.OptionGroupName = f62iter.OptionGroupName
				}
				if f62iter.Status != nil {
					f62elem.Status = f62iter.Status
				}
				f62 = append(f62, f62elem)
			}
			cr.Status.AtProvider.OptionGroupMemberships = f62
		} else {
			cr.Status.AtProvider.OptionGroupMemberships = nil
		}
		if elem.PendingModifiedValues != nil {
			f63 := &svcapitypes.PendingModifiedValues{}
			if elem.PendingModifiedValues.AdditionalStorageVolumes != nil {
				f63f0 := []*svcapitypes.AdditionalStorageVolume{}
				for _, f63f0iter := range elem.PendingModifiedValues.AdditionalStorageVolumes {
					f63f0elem := &svcapitypes.AdditionalStorageVolume{}
					if f63f0iter.AllocatedStorage != nil {
						allocatedStorageCopy := int64(*f63f0iter.AllocatedStorage)
						f63f0elem.AllocatedStorage = &allocatedStorageCopy
					}
					if f63f0iter.IOPS != nil {
						iopsCopy := int64(*f63f0iter.IOPS)
						f63f0elem.IOPS = &iopsCopy
					}
					if f63f0iter.MaxAllocatedStorage != nil {
						maxAllocatedStorageCopy := int64(*f63f0iter.MaxAllocatedStorage)
						f63f0elem.MaxAllocatedStorage = &maxAllocatedStorageCopy
					}
					if f63f0iter.StorageThroughput != nil {
						storageThroughputCopy := int64(*f63f0iter.StorageThroughput)
						f63f0elem.StorageThroughput = &storageThroughputCopy
					}
					if f63f0iter.StorageType != nil {
						f63f0elem.StorageType = f63f0iter.StorageType
					}
					if f63f0iter.VolumeName != nil {
						f63f0elem.VolumeName = f63f0iter.VolumeName
					}
					f63f0 = append(f63f0, f63f0elem)
				}
				f63.AdditionalStorageVolumes = f63f0
			}
			if elem.PendingModifiedValues.AllocatedStorage != nil {
				allocatedStorageCopy := int64(*elem.PendingModifiedValues.AllocatedStorage)
				f63.AllocatedStorage = &allocatedStorageCopy
			}
			if elem.PendingModifiedValues.AutomationMode != "" {
				f63.AutomationMode = aws.String(string(elem.PendingModifiedValues.AutomationMode))
			}
			if elem.PendingModifiedValues.BackupRetentionPeriod != nil {
				backupRetentionPeriodCopy := int64(*elem.PendingModifiedValues.BackupRetentionPeriod)
				f63.BackupRetentionPeriod = &backupRetentionPeriodCopy
			}
			if elem.PendingModifiedValues.CACertificateIdentifier != nil {
				f63.CACertificateIdentifier = elem.PendingModifiedValues.CACertificateIdentifier
			}
			if elem.PendingModifiedValues.DBInstanceClass != nil {
				f63.DBInstanceClass = elem.PendingModifiedValues.DBInstanceClass
			}
			if elem.PendingModifiedValues.DBInstanceIdentifier != nil {
				f63.DBInstanceIdentifier = elem.PendingModifiedValues.DBInstanceIdentifier
			}
			if elem.PendingModifiedValues.DBSubnetGroupName != nil {
				f63.DBSubnetGroupName = elem.PendingModifiedValues.DBSubnetGroupName
			}
			if elem.PendingModifiedValues.DedicatedLogVolume != nil {
				f63.DedicatedLogVolume = elem.PendingModifiedValues.DedicatedLogVolume
			}
			if elem.PendingModifiedValues.Engine != nil {
				f63.Engine = elem.PendingModifiedValues.Engine
			}
			if elem.PendingModifiedValues.EngineVersion != nil {
				f63.EngineVersion = elem.PendingModifiedValues.EngineVersion
			}
			if elem.PendingModifiedValues.IAMDatabaseAuthenticationEnabled != nil {
				f63.IAMDatabaseAuthenticationEnabled = elem.PendingModifiedValues.IAMDatabaseAuthenticationEnabled
			}
			if elem.PendingModifiedValues.Iops != nil {
				iopsCopy := int64(*elem.PendingModifiedValues.Iops)
				f63.IOPS = &iopsCopy
			}
			if elem.PendingModifiedValues.LicenseModel != nil {
				f63.LicenseModel = elem.PendingModifiedValues.LicenseModel
			}
			if elem.PendingModifiedValues.MasterUserPassword != nil {
				f63.MasterUserPassword = elem.PendingModifiedValues.MasterUserPassword
			}
			if elem.PendingModifiedValues.MultiAZ != nil {
				f63.MultiAZ = elem.PendingModifiedValues.MultiAZ
			}
			if elem.PendingModifiedValues.MultiTenant != nil {
				f63.MultiTenant = elem.PendingModifiedValues.MultiTenant
			}
			if elem.PendingModifiedValues.PendingCloudwatchLogsExports != nil {
				f63f17 := &svcapitypes.PendingCloudwatchLogsExports{}
				if elem.PendingModifiedValues.PendingCloudwatchLogsExports.LogTypesToDisable != nil {
					f63f17.LogTypesToDisable = aws.StringSlice(elem.PendingModifiedValues.PendingCloudwatchLogsExports.LogTypesToDisable)
				}
				if elem.PendingModifiedValues.PendingCloudwatchLogsExports.LogTypesToEnable != nil {
					f63f17.LogTypesToEnable = aws.StringSlice(elem.PendingModifiedValues.PendingCloudwatchLogsExports.LogTypesToEnable)
				}
				f63.PendingCloudwatchLogsExports = f63f17
			}
			if elem.PendingModifiedValues.Port != nil {
				portCopy := int64(*elem.PendingModifiedValues.Port)
				f63.Port = &portCopy
			}
			if elem.PendingModifiedValues.ProcessorFeatures != nil {
				f63f19 := []*svcapitypes.ProcessorFeature{}
				for _, f63f19iter := range elem.PendingModifiedValues.ProcessorFeatures {
					f63f19elem := &svcapitypes.ProcessorFeature{}
					if f63f19iter.Name != nil {
						f63f19elem.Name = f63f19iter.Name
					}
					if f63f19iter.Value != nil {
						f63f19elem.Value = f63f19iter.Value
					}
					f63f19 = append(f63f19, f63f19elem)
				}
				f63.ProcessorFeatures = f63f19
			}
			if elem.PendingModifiedValues.ResumeFullAutomationModeTime != nil {
				f63.ResumeFullAutomationModeTime = &metav1.Time{Time: *elem.PendingModifiedValues.ResumeFullAutomationModeTime}
			}
			if elem.PendingModifiedValues.StorageThroughput != nil {
				storageThroughputCopy := int64(*elem.PendingModifiedValues.StorageThroughput)
				f63.StorageThroughput = &storageThroughputCopy
			}
			if elem.PendingModifiedValues.StorageType != nil {
				f63.StorageType = elem.PendingModifiedValues.StorageType
			}
			cr.Status.AtProvider.PendingModifiedValues = f63
		} else {
			cr.Status.AtProvider.PendingModifiedValues = nil
		}
		if elem.PercentProgress != nil {
			cr.Status.AtProvider.PercentProgress = elem.PercentProgress
		} else {
			cr.Status.AtProvider.PercentProgress = nil
		}
		if elem.PerformanceInsightsEnabled != nil {
			cr.Status.AtProvider.PerformanceInsightsEnabled = elem.PerformanceInsightsEnabled
		} else {
			cr.Status.AtProvider.PerformanceInsightsEnabled = nil
		}
		if elem.PerformanceInsightsKMSKeyId != nil {
			cr.Spec.ForProvider.PerformanceInsightsKMSKeyID = elem.PerformanceInsightsKMSKeyId
		} else {
			cr.Spec.ForProvider.PerformanceInsightsKMSKeyID = nil
		}
		if elem.PerformanceInsightsRetentionPeriod != nil {
			performanceInsightsRetentionPeriodCopy := int64(*elem.PerformanceInsightsRetentionPeriod)
			cr.Spec.ForProvider.PerformanceInsightsRetentionPeriod = &performanceInsightsRetentionPeriodCopy
		} else {
			cr.Spec.ForProvider.PerformanceInsightsRetentionPeriod = nil
		}
		if elem.PreferredBackupWindow != nil {
			cr.Spec.ForProvider.PreferredBackupWindow = elem.PreferredBackupWindow
		} else {
			cr.Spec.ForProvider.PreferredBackupWindow = nil
		}
		if elem.PreferredMaintenanceWindow != nil {
			cr.Spec.ForProvider.PreferredMaintenanceWindow = elem.PreferredMaintenanceWindow
		} else {
			cr.Spec.ForProvider.PreferredMaintenanceWindow = nil
		}
		if elem.ProcessorFeatures != nil {
			f70 := []*svcapitypes.ProcessorFeature{}
			for _, f70iter := range elem.ProcessorFeatures {
				f70elem := &svcapitypes.ProcessorFeature{}
				if f70iter.Name != nil {
					f70elem.Name = f70iter.Name
				}
				if f70iter.Value != nil {
					f70elem.Value = f70iter.Value
				}
				f70 = append(f70, f70elem)
			}
			cr.Spec.ForProvider.ProcessorFeatures = f70
		} else {
			cr.Spec.ForProvider.ProcessorFeatures = nil
		}
		if elem.PromotionTier != nil {
			promotionTierCopy := int64(*elem.PromotionTier)
			cr.Spec.ForProvider.PromotionTier = &promotionTierCopy
		} else {
			cr.Spec.ForProvider.PromotionTier = nil
		}
		if elem.PubliclyAccessible != nil {
			cr.Spec.ForProvider.PubliclyAccessible = elem.PubliclyAccessible
		} else {
			cr.Spec.ForProvider.PubliclyAccessible = nil
		}
		if elem.ReadReplicaDBClusterIdentifiers != nil {
			cr.Status.AtProvider.ReadReplicaDBClusterIdentifiers = aws.StringSlice(elem.ReadReplicaDBClusterIdentifiers)
		} else {
			cr.Status.AtProvider.ReadReplicaDBClusterIdentifiers = nil
		}
		if elem.ReadReplicaDBInstanceIdentifiers != nil {
			cr.Status.AtProvider.ReadReplicaDBInstanceIdentifiers = aws.StringSlice(elem.ReadReplicaDBInstanceIdentifiers)
		} else {
			cr.Status.AtProvider.ReadReplicaDBInstanceIdentifiers = nil
		}
		if elem.ReadReplicaSourceDBClusterIdentifier != nil {
			cr.Status.AtProvider.ReadReplicaSourceDBClusterIdentifier = elem.ReadReplicaSourceDBClusterIdentifier
		} else {
			cr.Status.AtProvider.ReadReplicaSourceDBClusterIdentifier = nil
		}
		if elem.ReadReplicaSourceDBInstanceIdentifier != nil {
			cr.Status.AtProvider.ReadReplicaSourceDBInstanceIdentifier = elem.ReadReplicaSourceDBInstanceIdentifier
		} else {
			cr.Status.AtProvider.ReadReplicaSourceDBInstanceIdentifier = nil
		}
		if elem.ReplicaMode != "" {
			cr.Status.AtProvider.ReplicaMode = aws.String(string(elem.ReplicaMode))
		} else {
			cr.Status.AtProvider.ReplicaMode = nil
		}
		if elem.ResumeFullAutomationModeTime != nil {
			cr.Status.AtProvider.ResumeFullAutomationModeTime = &metav1.Time{Time: *elem.ResumeFullAutomationModeTime}
		} else {
			cr.Status.AtProvider.ResumeFullAutomationModeTime = nil
		}
		if elem.SecondaryAvailabilityZone != nil {
			cr.Status.AtProvider.SecondaryAvailabilityZone = elem.SecondaryAvailabilityZone
		} else {
			cr.Status.AtProvider.SecondaryAvailabilityZone = nil
		}
		if elem.StatusInfos != nil {
			f80 := []*svcapitypes.DBInstanceStatusInfo{}
			for _, f80iter := range elem.StatusInfos {
				f80elem := &svcapitypes.DBInstanceStatusInfo{}
				if f80iter.Message != nil {
					f80elem.Message = f80iter.Message
				}
				if f80iter.Normal != nil {
					f80elem.Normal = f80iter.Normal
				}
				if f80iter.Status != nil {
					f80elem.Status = f80iter.Status
				}
				if f80iter.StatusType != nil {
					f80elem.StatusType = f80iter.StatusType
				}
				f80 = append(f80, f80elem)
			}
			cr.Status.AtProvider.StatusInfos = f80
		} else {
			cr.Status.AtProvider.StatusInfos = nil
		}
		if elem.StorageEncrypted != nil {
			cr.Spec.ForProvider.StorageEncrypted = elem.StorageEncrypted
		} else {
			cr.Spec.ForProvider.StorageEncrypted = nil
		}
		if elem.StorageEncryptionType != "" {
			cr.Status.AtProvider.StorageEncryptionType = aws.String(string(elem.StorageEncryptionType))
		} else {
			cr.Status.AtProvider.StorageEncryptionType = nil
		}
		if elem.StorageOperationPercentProgress != nil {
			storageOperationPercentProgressCopy := int64(*elem.StorageOperationPercentProgress)
			cr.Status.AtProvider.StorageOperationPercentProgress = &storageOperationPercentProgressCopy
		} else {
			cr.Status.AtProvider.StorageOperationPercentProgress = nil
		}
		if elem.StorageOperationStatus != nil {
			cr.Status.AtProvider.StorageOperationStatus = elem.StorageOperationStatus
		} else {
			cr.Status.AtProvider.StorageOperationStatus = nil
		}
		if elem.StorageThroughput != nil {
			storageThroughputCopy := int64(*elem.StorageThroughput)
			cr.Spec.ForProvider.StorageThroughput = &storageThroughputCopy
		} else {
			cr.Spec.ForProvider.StorageThroughput = nil
		}
		if elem.StorageType != nil {
			cr.Spec.ForProvider.StorageType = elem.StorageType
		} else {
			cr.Spec.ForProvider.StorageType = nil
		}
		if elem.StorageVolumeStatus != nil {
			cr.Status.AtProvider.StorageVolumeStatus = elem.StorageVolumeStatus
		} else {
			cr.Status.AtProvider.StorageVolumeStatus = nil
		}
		if elem.TagList != nil {
			f88 := []*svcapitypes.Tag{}
			for _, f88iter := range elem.TagList {
				f88elem := &svcapitypes.Tag{}
				if f88iter.Key != nil {
					f88elem.Key = f88iter.Key
				}
				if f88iter.Value != nil {
					f88elem.Value = f88iter.Value
				}
				f88 = append(f88, f88elem)
			}
			cr.Status.AtProvider.TagList = f88
		} else {
			cr.Status.AtProvider.TagList = nil
		}
		if elem.TdeCredentialArn != nil {
			cr.Spec.ForProvider.TDECredentialARN = elem.TdeCredentialArn
		} else {
			cr.Spec.ForProvider.TDECredentialARN = nil
		}
		if elem.Timezone != nil {
			cr.Spec.ForProvider.Timezone = elem.Timezone
		} else {
			cr.Spec.ForProvider.Timezone = nil
		}
		if elem.UpgradeRolloutOrder != "" {
			cr.Status.AtProvider.UpgradeRolloutOrder = aws.String(string(elem.UpgradeRolloutOrder))
		} else {
			cr.Status.AtProvider.UpgradeRolloutOrder = nil
		}
		if elem.VpcSecurityGroups != nil {
			f92 := []*svcapitypes.VPCSecurityGroupMembership{}
			for _, f92iter := range elem.VpcSecurityGroups {
				f92elem := &svcapitypes.VPCSecurityGroupMembership{}
				if f92iter.Status != nil {
					f92elem.Status = f92iter.Status
				}
				if f92iter.VpcSecurityGroupId != nil {
					f92elem.VPCSecurityGroupID = f92iter.VpcSecurityGroupId
				}
				f92 = append(f92, f92elem)
			}
			cr.Status.AtProvider.VPCSecurityGroups = f92
		} else {
			cr.Status.AtProvider.VPCSecurityGroups = nil
		}
		found = true
		break
	}
	if !found {
		return cr
	}

	return cr
}

// GenerateCreateDBInstanceInput returns a create input.
func GenerateCreateDBInstanceInput(cr *svcapitypes.DBInstance) (*svcsdk.CreateDBInstanceInput, error) {
	res := &svcsdk.CreateDBInstanceInput{}

	if cr.Spec.ForProvider.AdditionalStorageVolumes != nil {
		f0 := []svcsdktypes.AdditionalStorageVolume{}
		for _, f0iter := range cr.Spec.ForProvider.AdditionalStorageVolumes {
			f0elem := &svcsdktypes.AdditionalStorageVolume{}
			if f0iter.AllocatedStorage != nil {
				allocatedStorageCopy0 := *f0iter.AllocatedStorage
				if allocatedStorageCopy0 > math.MaxInt32 || allocatedStorageCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field AllocatedStorage is of type int32")
				}
				allocatedStorageCopy := int32(allocatedStorageCopy0)
				f0elem.AllocatedStorage = &allocatedStorageCopy
			}
			if f0iter.IOPS != nil {
				iopsCopy0 := *f0iter.IOPS
				if iopsCopy0 > math.MaxInt32 || iopsCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field IOPS is of type int32")
				}
				iopsCopy := int32(iopsCopy0)
				f0elem.IOPS = &iopsCopy
			}
			if f0iter.MaxAllocatedStorage != nil {
				maxAllocatedStorageCopy0 := *f0iter.MaxAllocatedStorage
				if maxAllocatedStorageCopy0 > math.MaxInt32 || maxAllocatedStorageCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field MaxAllocatedStorage is of type int32")
				}
				maxAllocatedStorageCopy := int32(maxAllocatedStorageCopy0)
				f0elem.MaxAllocatedStorage = &maxAllocatedStorageCopy
			}
			if f0iter.StorageThroughput != nil {
				storageThroughputCopy0 := *f0iter.StorageThroughput
				if storageThroughputCopy0 > math.MaxInt32 || storageThroughputCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field StorageThroughput is of type int32")
				}
				storageThroughputCopy := int32(storageThroughputCopy0)
				f0elem.StorageThroughput = &storageThroughputCopy
			}
			if f0iter.StorageType != nil {
				f0elem.StorageType = f0iter.StorageType
			}
			if f0iter.VolumeName != nil {
				f0elem.VolumeName = f0iter.VolumeName
			}
			f0 = append(f0, *f0elem)
		}
		res.AdditionalStorageVolumes = f0
	}
	if cr.Spec.ForProvider.AllocatedStorage != nil {
		allocatedStorageCopy0 := *cr.Spec.ForProvider.AllocatedStorage
		if allocatedStorageCopy0 > math.MaxInt32 || allocatedStorageCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field AllocatedStorage is of type int32")
		}
		allocatedStorageCopy := int32(allocatedStorageCopy0)
		res.AllocatedStorage = &allocatedStorageCopy
	}
	if cr.Spec.ForProvider.AutoMinorVersionUpgrade != nil {
		res.AutoMinorVersionUpgrade = cr.Spec.ForProvider.AutoMinorVersionUpgrade
	}
	if cr.Spec.ForProvider.AvailabilityZone != nil {
		res.AvailabilityZone = cr.Spec.ForProvider.AvailabilityZone
	}
	if cr.Spec.ForProvider.BackupRetentionPeriod != nil {
		backupRetentionPeriodCopy0 := *cr.Spec.ForProvider.BackupRetentionPeriod
		if backupRetentionPeriodCopy0 > math.MaxInt32 || backupRetentionPeriodCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field BackupRetentionPeriod is of type int32")
		}
		backupRetentionPeriodCopy := int32(backupRetentionPeriodCopy0)
		res.BackupRetentionPeriod = &backupRetentionPeriodCopy
	}
	if cr.Spec.ForProvider.BackupTarget != nil {
		res.BackupTarget = cr.Spec.ForProvider.BackupTarget
	}
	if cr.Spec.ForProvider.CACertificateIdentifier != nil {
		res.CACertificateIdentifier = cr.Spec.ForProvider.CACertificateIdentifier
	}
	if cr.Spec.ForProvider.CharacterSetName != nil {
		res.CharacterSetName = cr.Spec.ForProvider.CharacterSetName
	}
	if cr.Spec.ForProvider.CopyTagsToSnapshot != nil {
		res.CopyTagsToSnapshot = cr.Spec.ForProvider.CopyTagsToSnapshot
	}
	if cr.Spec.ForProvider.CustomIAMInstanceProfile != nil {
		res.CustomIamInstanceProfile = cr.Spec.ForProvider.CustomIAMInstanceProfile
	}
	if cr.Spec.ForProvider.DBClusterIdentifier != nil {
		res.DBClusterIdentifier = cr.Spec.ForProvider.DBClusterIdentifier
	}
	if cr.Spec.ForProvider.DBInstanceClass != nil {
		res.DBInstanceClass = cr.Spec.ForProvider.DBInstanceClass
	}
	if cr.Spec.ForProvider.DBName != nil {
		res.DBName = cr.Spec.ForProvider.DBName
	}
	if cr.Spec.ForProvider.DBParameterGroupName != nil {
		res.DBParameterGroupName = cr.Spec.ForProvider.DBParameterGroupName
	}
	if cr.Spec.ForProvider.DBSubnetGroupName != nil {
		res.DBSubnetGroupName = cr.Spec.ForProvider.DBSubnetGroupName
	}
	if cr.Spec.ForProvider.DBSystemID != nil {
		res.DBSystemId = cr.Spec.ForProvider.DBSystemID
	}
	if cr.Spec.ForProvider.DatabaseInsightsMode != nil {
		res.DatabaseInsightsMode = svcsdktypes.DatabaseInsightsMode(*cr.Spec.ForProvider.DatabaseInsightsMode)
	}
	if cr.Spec.ForProvider.DedicatedLogVolume != nil {
		res.DedicatedLogVolume = cr.Spec.ForProvider.DedicatedLogVolume
	}
	if cr.Spec.ForProvider.DeletionProtection != nil {
		res.DeletionProtection = cr.Spec.ForProvider.DeletionProtection
	}
	if cr.Spec.ForProvider.Domain != nil {
		res.Domain = cr.Spec.ForProvider.Domain
	}
	if cr.Spec.ForProvider.DomainAuthSecretARN != nil {
		res.DomainAuthSecretArn = cr.Spec.ForProvider.DomainAuthSecretARN
	}
	if cr.Spec.ForProvider.DomainDNSIPs != nil {
		res.DomainDnsIps = aws.ToStringSlice(cr.Spec.ForProvider.DomainDNSIPs)
	}
	if cr.Spec.ForProvider.DomainFqdn != nil {
		res.DomainFqdn = cr.Spec.ForProvider.DomainFqdn
	}
	if cr.Spec.ForProvider.DomainIAMRoleName != nil {
		res.DomainIAMRoleName = cr.Spec.ForProvider.DomainIAMRoleName
	}
	if cr.Spec.ForProvider.DomainOu != nil {
		res.DomainOu = cr.Spec.ForProvider.DomainOu
	}
	if cr.Spec.ForProvider.EnableCloudwatchLogsExports != nil {
		res.EnableCloudwatchLogsExports = aws.ToStringSlice(cr.Spec.ForProvider.EnableCloudwatchLogsExports)
	}
	if cr.Spec.ForProvider.EnableCustomerOwnedIP != nil {
		res.EnableCustomerOwnedIp = cr.Spec.ForProvider.EnableCustomerOwnedIP
	}
	if cr.Spec.ForProvider.EnableIAMDatabaseAuthentication != nil {
		res.EnableIAMDatabaseAuthentication = cr.Spec.ForProvider.EnableIAMDatabaseAuthentication
	}
	if cr.Spec.ForProvider.EnablePerformanceInsights != nil {
		res.EnablePerformanceInsights = cr.Spec.ForProvider.EnablePerformanceInsights
	}
	if cr.Spec.ForProvider.Engine != nil {
		res.Engine = cr.Spec.ForProvider.Engine
	}
	if cr.Spec.ForProvider.EngineLifecycleSupport != nil {
		res.EngineLifecycleSupport = cr.Spec.ForProvider.EngineLifecycleSupport
	}
	if cr.Spec.ForProvider.IOPS != nil {
		iopsCopy0 := *cr.Spec.ForProvider.IOPS
		if iopsCopy0 > math.MaxInt32 || iopsCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field Iops is of type int32")
		}
		iopsCopy := int32(iopsCopy0)
		res.Iops = &iopsCopy
	}
	if cr.Spec.ForProvider.KMSKeyID != nil {
		res.KmsKeyId = cr.Spec.ForProvider.KMSKeyID
	}
	if cr.Spec.ForProvider.LicenseModel != nil {
		res.LicenseModel = cr.Spec.ForProvider.LicenseModel
	}
	if cr.Spec.ForProvider.ManageMasterUserPassword != nil {
		res.ManageMasterUserPassword = cr.Spec.ForProvider.ManageMasterUserPassword
	}
	if cr.Spec.ForProvider.MasterUserAuthenticationType != nil {
		res.MasterUserAuthenticationType = svcsdktypes.MasterUserAuthenticationType(*cr.Spec.ForProvider.MasterUserAuthenticationType)
	}
	if cr.Spec.ForProvider.MasterUserSecretKMSKeyID != nil {
		res.MasterUserSecretKmsKeyId = cr.Spec.ForProvider.MasterUserSecretKMSKeyID
	}
	if cr.Spec.ForProvider.MasterUsername != nil {
		res.MasterUsername = cr.Spec.ForProvider.MasterUsername
	}
	if cr.Spec.ForProvider.MaxAllocatedStorage != nil {
		maxAllocatedStorageCopy0 := *cr.Spec.ForProvider.MaxAllocatedStorage
		if maxAllocatedStorageCopy0 > math.MaxInt32 || maxAllocatedStorageCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field MaxAllocatedStorage is of type int32")
		}
		maxAllocatedStorageCopy := int32(maxAllocatedStorageCopy0)
		res.MaxAllocatedStorage = &maxAllocatedStorageCopy
	}
	if cr.Spec.ForProvider.MonitoringInterval != nil {
		monitoringIntervalCopy0 := *cr.Spec.ForProvider.MonitoringInterval
		if monitoringIntervalCopy0 > math.MaxInt32 || monitoringIntervalCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field MonitoringInterval is of type int32")
		}
		monitoringIntervalCopy := int32(monitoringIntervalCopy0)
		res.MonitoringInterval = &monitoringIntervalCopy
	}
	if cr.Spec.ForProvider.MonitoringRoleARN != nil {
		res.MonitoringRoleArn = cr.Spec.ForProvider.MonitoringRoleARN
	}
	if cr.Spec.ForProvider.MultiAZ != nil {
		res.MultiAZ = cr.Spec.ForProvider.MultiAZ
	}
	if cr.Spec.ForProvider.MultiTenant != nil {
		res.MultiTenant = cr.Spec.ForProvider.MultiTenant
	}
	if cr.Spec.ForProvider.NcharCharacterSetName != nil {
		res.NcharCharacterSetName = cr.Spec.ForProvider.NcharCharacterSetName
	}
	if cr.Spec.ForProvider.NetworkType != nil {
		res.NetworkType = cr.Spec.ForProvider.NetworkType
	}
	if cr.Spec.ForProvider.OptionGroupName != nil {
		res.OptionGroupName = cr.Spec.ForProvider.OptionGroupName
	}
	if cr.Spec.ForProvider.PerformanceInsightsKMSKeyID != nil {
		res.PerformanceInsightsKMSKeyId = cr.Spec.ForProvider.PerformanceInsightsKMSKeyID
	}
	if cr.Spec.ForProvider.PerformanceInsightsRetentionPeriod != nil {
		performanceInsightsRetentionPeriodCopy0 := *cr.Spec.ForProvider.PerformanceInsightsRetentionPeriod
		if performanceInsightsRetentionPeriodCopy0 > math.MaxInt32 || performanceInsightsRetentionPeriodCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field PerformanceInsightsRetentionPeriod is of type int32")
		}
		performanceInsightsRetentionPeriodCopy := int32(performanceInsightsRetentionPeriodCopy0)
		res.PerformanceInsightsRetentionPeriod = &performanceInsightsRetentionPeriodCopy
	}
	if cr.Spec.ForProvider.Port != nil {
		portCopy0 := *cr.Spec.ForProvider.Port
		if portCopy0 > math.MaxInt32 || portCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field Port is of type int32")
		}
		portCopy := int32(portCopy0)
		res.Port = &portCopy
	}
	if cr.Spec.ForProvider.PreferredBackupWindow != nil {
		res.PreferredBackupWindow = cr.Spec.ForProvider.PreferredBackupWindow
	}
	if cr.Spec.ForProvider.PreferredMaintenanceWindow != nil {
		res.PreferredMaintenanceWindow = cr.Spec.ForProvider.PreferredMaintenanceWindow
	}
	if cr.Spec.ForProvider.ProcessorFeatures != nil {
		f51 := []svcsdktypes.ProcessorFeature{}
		for _, f51iter := range cr.Spec.ForProvider.ProcessorFeatures {
			f51elem := &svcsdktypes.ProcessorFeature{}
			if f51iter.Name != nil {
				f51elem.Name = f51iter.Name
			}
			if f51iter.Value != nil {
				f51elem.Value = f51iter.Value
			}
			f51 = append(f51, *f51elem)
		}
		res.ProcessorFeatures = f51
	}
	if cr.Spec.ForProvider.PromotionTier != nil {
		promotionTierCopy0 := *cr.Spec.ForProvider.PromotionTier
		if promotionTierCopy0 > math.MaxInt32 || promotionTierCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field PromotionTier is of type int32")
		}
		promotionTierCopy := int32(promotionTierCopy0)
		res.PromotionTier = &promotionTierCopy
	}
	if cr.Spec.ForProvider.PubliclyAccessible != nil {
		res.PubliclyAccessible = cr.Spec.ForProvider.PubliclyAccessible
	}
	if cr.Spec.ForProvider.StorageEncrypted != nil {
		res.StorageEncrypted = cr.Spec.ForProvider.StorageEncrypted
	}
	if cr.Spec.ForProvider.StorageThroughput != nil {
		storageThroughputCopy0 := *cr.Spec.ForProvider.StorageThroughput
		if storageThroughputCopy0 > math.MaxInt32 || storageThroughputCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field StorageThroughput is of type int32")
		}
		storageThroughputCopy := int32(storageThroughputCopy0)
		res.StorageThroughput = &storageThroughputCopy
	}
	if cr.Spec.ForProvider.StorageType != nil {
		res.StorageType = cr.Spec.ForProvider.StorageType
	}
	if cr.Spec.ForProvider.TagSpecifications != nil {
		f57 := []svcsdktypes.TagSpecification{}
		for _, f57iter := range cr.Spec.ForProvider.TagSpecifications {
			f57elem := &svcsdktypes.TagSpecification{}
			if f57iter.ResourceType != nil {
				f57elem.ResourceType = f57iter.ResourceType
			}
			if f57iter.Tags != nil {
				f57elemf1 := []svcsdktypes.Tag{}
				for _, f57elemf1iter := range f57iter.Tags {
					f57elemf1elem := &svcsdktypes.Tag{}
					if f57elemf1iter.Key != nil {
						f57elemf1elem.Key = f57elemf1iter.Key
					}
					if f57elemf1iter.Value != nil {
						f57elemf1elem.Value = f57elemf1iter.Value
					}
					f57elemf1 = append(f57elemf1, *f57elemf1elem)
				}
				f57elem.Tags = f57elemf1
			}
			f57 = append(f57, *f57elem)
		}
		res.TagSpecifications = f57
	}
	if cr.Spec.ForProvider.Tags != nil {
		f58 := []svcsdktypes.Tag{}
		for _, f58iter := range cr.Spec.ForProvider.Tags {
			f58elem := &svcsdktypes.Tag{}
			if f58iter.Key != nil {
				f58elem.Key = f58iter.Key
			}
			if f58iter.Value != nil {
				f58elem.Value = f58iter.Value
			}
			f58 = append(f58, *f58elem)
		}
		res.Tags = f58
	}
	if cr.Spec.ForProvider.TDECredentialARN != nil {
		res.TdeCredentialArn = cr.Spec.ForProvider.TDECredentialARN
	}
	if cr.Spec.ForProvider.TDECredentialPassword != nil {
		res.TdeCredentialPassword = cr.Spec.ForProvider.TDECredentialPassword
	}
	if cr.Spec.ForProvider.Timezone != nil {
		res.Timezone = cr.Spec.ForProvider.Timezone
	}

	return res, nil
}

// GenerateModifyDBInstanceInput returns an update input.
func GenerateModifyDBInstanceInput(cr *svcapitypes.DBInstance) (*svcsdk.ModifyDBInstanceInput, error) {
	res := &svcsdk.ModifyDBInstanceInput{}

	if cr.Spec.ForProvider.AdditionalStorageVolumes != nil {
		f0 := []svcsdktypes.ModifyAdditionalStorageVolume{}
		for _, f0iter := range cr.Spec.ForProvider.AdditionalStorageVolumes {
			f0elem := &svcsdktypes.ModifyAdditionalStorageVolume{}
			if f0iter.AllocatedStorage != nil {
				allocatedStorageCopy0 := *f0iter.AllocatedStorage
				if allocatedStorageCopy0 > math.MaxInt32 || allocatedStorageCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field AllocatedStorage is of type int32")
				}
				allocatedStorageCopy := int32(allocatedStorageCopy0)
				f0elem.AllocatedStorage = &allocatedStorageCopy
			}
			if f0iter.IOPS != nil {
				iopsCopy0 := *f0iter.IOPS
				if iopsCopy0 > math.MaxInt32 || iopsCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field IOPS is of type int32")
				}
				iopsCopy := int32(iopsCopy0)
				f0elem.IOPS = &iopsCopy
			}
			if f0iter.MaxAllocatedStorage != nil {
				maxAllocatedStorageCopy0 := *f0iter.MaxAllocatedStorage
				if maxAllocatedStorageCopy0 > math.MaxInt32 || maxAllocatedStorageCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field MaxAllocatedStorage is of type int32")
				}
				maxAllocatedStorageCopy := int32(maxAllocatedStorageCopy0)
				f0elem.MaxAllocatedStorage = &maxAllocatedStorageCopy
			}
			if f0iter.StorageThroughput != nil {
				storageThroughputCopy0 := *f0iter.StorageThroughput
				if storageThroughputCopy0 > math.MaxInt32 || storageThroughputCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field StorageThroughput is of type int32")
				}
				storageThroughputCopy := int32(storageThroughputCopy0)
				f0elem.StorageThroughput = &storageThroughputCopy
			}
			if f0iter.StorageType != nil {
				f0elem.StorageType = f0iter.StorageType
			}
			if f0iter.VolumeName != nil {
				f0elem.VolumeName = f0iter.VolumeName
			}
			f0 = append(f0, *f0elem)
		}
		res.AdditionalStorageVolumes = f0
	}
	if cr.Spec.ForProvider.AllocatedStorage != nil {
		allocatedStorageCopy0 := *cr.Spec.ForProvider.AllocatedStorage
		if allocatedStorageCopy0 > math.MaxInt32 || allocatedStorageCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field AllocatedStorage is of type int32")
		}
		allocatedStorageCopy := int32(allocatedStorageCopy0)
		res.AllocatedStorage = &allocatedStorageCopy
	}
	if cr.Spec.ForProvider.AllowMajorVersionUpgrade != nil {
		res.AllowMajorVersionUpgrade = cr.Spec.ForProvider.AllowMajorVersionUpgrade
	}
	if cr.Spec.ForProvider.AutoMinorVersionUpgrade != nil {
		res.AutoMinorVersionUpgrade = cr.Spec.ForProvider.AutoMinorVersionUpgrade
	}
	if cr.Status.AtProvider.AutomationMode != nil {
		res.AutomationMode = svcsdktypes.AutomationMode(*cr.Status.AtProvider.AutomationMode)
	}
	if cr.Status.AtProvider.AWSBackupRecoveryPointARN != nil {
		res.AwsBackupRecoveryPointArn = cr.Status.AtProvider.AWSBackupRecoveryPointARN
	}
	if cr.Spec.ForProvider.BackupRetentionPeriod != nil {
		backupRetentionPeriodCopy0 := *cr.Spec.ForProvider.BackupRetentionPeriod
		if backupRetentionPeriodCopy0 > math.MaxInt32 || backupRetentionPeriodCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field BackupRetentionPeriod is of type int32")
		}
		backupRetentionPeriodCopy := int32(backupRetentionPeriodCopy0)
		res.BackupRetentionPeriod = &backupRetentionPeriodCopy
	}
	if cr.Spec.ForProvider.CACertificateIdentifier != nil {
		res.CACertificateIdentifier = cr.Spec.ForProvider.CACertificateIdentifier
	}
	if cr.Spec.ForProvider.CopyTagsToSnapshot != nil {
		res.CopyTagsToSnapshot = cr.Spec.ForProvider.CopyTagsToSnapshot
	}
	if cr.Spec.ForProvider.DBInstanceClass != nil {
		res.DBInstanceClass = cr.Spec.ForProvider.DBInstanceClass
	}
	if cr.Spec.ForProvider.DBParameterGroupName != nil {
		res.DBParameterGroupName = cr.Spec.ForProvider.DBParameterGroupName
	}
	if cr.Spec.ForProvider.DatabaseInsightsMode != nil {
		res.DatabaseInsightsMode = svcsdktypes.DatabaseInsightsMode(*cr.Spec.ForProvider.DatabaseInsightsMode)
	}
	if cr.Spec.ForProvider.DedicatedLogVolume != nil {
		res.DedicatedLogVolume = cr.Spec.ForProvider.DedicatedLogVolume
	}
	if cr.Spec.ForProvider.DeletionProtection != nil {
		res.DeletionProtection = cr.Spec.ForProvider.DeletionProtection
	}
	if cr.Spec.ForProvider.Domain != nil {
		res.Domain = cr.Spec.ForProvider.Domain
	}
	if cr.Spec.ForProvider.DomainAuthSecretARN != nil {
		res.DomainAuthSecretArn = cr.Spec.ForProvider.DomainAuthSecretARN
	}
	if cr.Spec.ForProvider.DomainDNSIPs != nil {
		res.DomainDnsIps = aws.ToStringSlice(cr.Spec.ForProvider.DomainDNSIPs)
	}
	if cr.Spec.ForProvider.DomainFqdn != nil {
		res.DomainFqdn = cr.Spec.ForProvider.DomainFqdn
	}
	if cr.Spec.ForProvider.DomainIAMRoleName != nil {
		res.DomainIAMRoleName = cr.Spec.ForProvider.DomainIAMRoleName
	}
	if cr.Spec.ForProvider.DomainOu != nil {
		res.DomainOu = cr.Spec.ForProvider.DomainOu
	}
	if cr.Spec.ForProvider.EnableCustomerOwnedIP != nil {
		res.EnableCustomerOwnedIp = cr.Spec.ForProvider.EnableCustomerOwnedIP
	}
	if cr.Spec.ForProvider.EnableIAMDatabaseAuthentication != nil {
		res.EnableIAMDatabaseAuthentication = cr.Spec.ForProvider.EnableIAMDatabaseAuthentication
	}
	if cr.Spec.ForProvider.EnablePerformanceInsights != nil {
		res.EnablePerformanceInsights = cr.Spec.ForProvider.EnablePerformanceInsights
	}
	if cr.Spec.ForProvider.Engine != nil {
		res.Engine = cr.Spec.ForProvider.Engine
	}
	if cr.Spec.ForProvider.EngineLifecycleSupport != nil {
		res.EngineLifecycleSupport = cr.Spec.ForProvider.EngineLifecycleSupport
	}
	if cr.Spec.ForProvider.IOPS != nil {
		iopsCopy0 := *cr.Spec.ForProvider.IOPS
		if iopsCopy0 > math.MaxInt32 || iopsCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field Iops is of type int32")
		}
		iopsCopy := int32(iopsCopy0)
		res.Iops = &iopsCopy
	}
	if cr.Spec.ForProvider.LicenseModel != nil {
		res.LicenseModel = cr.Spec.ForProvider.LicenseModel
	}
	if cr.Spec.ForProvider.ManageMasterUserPassword != nil {
		res.ManageMasterUserPassword = cr.Spec.ForProvider.ManageMasterUserPassword
	}
	if cr.Spec.ForProvider.MasterUserAuthenticationType != nil {
		res.MasterUserAuthenticationType = svcsdktypes.MasterUserAuthenticationType(*cr.Spec.ForProvider.MasterUserAuthenticationType)
	}
	if cr.Spec.ForProvider.MasterUserSecretKMSKeyID != nil {
		res.MasterUserSecretKmsKeyId = cr.Spec.ForProvider.MasterUserSecretKMSKeyID
	}
	if cr.Spec.ForProvider.MaxAllocatedStorage != nil {
		maxAllocatedStorageCopy0 := *cr.Spec.ForProvider.MaxAllocatedStorage
		if maxAllocatedStorageCopy0 > math.MaxInt32 || maxAllocatedStorageCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field MaxAllocatedStorage is of type int32")
		}
		maxAllocatedStorageCopy := int32(maxAllocatedStorageCopy0)
		res.MaxAllocatedStorage = &maxAllocatedStorageCopy
	}
	if cr.Spec.ForProvider.MonitoringInterval != nil {
		monitoringIntervalCopy0 := *cr.Spec.ForProvider.MonitoringInterval
		if monitoringIntervalCopy0 > math.MaxInt32 || monitoringIntervalCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field MonitoringInterval is of type int32")
		}
		monitoringIntervalCopy := int32(monitoringIntervalCopy0)
		res.MonitoringInterval = &monitoringIntervalCopy
	}
	if cr.Spec.ForProvider.MonitoringRoleARN != nil {
		res.MonitoringRoleArn = cr.Spec.ForProvider.MonitoringRoleARN
	}
	if cr.Spec.ForProvider.MultiAZ != nil {
		res.MultiAZ = cr.Spec.ForProvider.MultiAZ
	}
	if cr.Spec.ForProvider.MultiTenant != nil {
		res.MultiTenant = cr.Spec.ForProvider.MultiTenant
	}
	if cr.Spec.ForProvider.NetworkType != nil {
		res.NetworkType = cr.Spec.ForProvider.NetworkType
	}
	if cr.Spec.ForProvider.OptionGroupName != nil {
		res.OptionGroupName = cr.Spec.ForProvider.OptionGroupName
	}
	if cr.Spec.ForProvider.PerformanceInsightsKMSKeyID != nil {
		res.PerformanceInsightsKMSKeyId = cr.Spec.ForProvider.PerformanceInsightsKMSKeyID
	}
	if cr.Spec.ForProvider.PerformanceInsightsRetentionPeriod != nil {
		performanceInsightsRetentionPeriodCopy0 := *cr.Spec.ForProvider.PerformanceInsightsRetentionPeriod
		if performanceInsightsRetentionPeriodCopy0 > math.MaxInt32 || performanceInsightsRetentionPeriodCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field PerformanceInsightsRetentionPeriod is of type int32")
		}
		performanceInsightsRetentionPeriodCopy := int32(performanceInsightsRetentionPeriodCopy0)
		res.PerformanceInsightsRetentionPeriod = &performanceInsightsRetentionPeriodCopy
	}
	if cr.Spec.ForProvider.PreferredBackupWindow != nil {
		res.PreferredBackupWindow = cr.Spec.ForProvider.PreferredBackupWindow
	}
	if cr.Spec.ForProvider.PreferredMaintenanceWindow != nil {
		res.PreferredMaintenanceWindow = cr.Spec.ForProvider.PreferredMaintenanceWindow
	}
	if cr.Spec.ForProvider.ProcessorFeatures != nil {
		f47 := []svcsdktypes.ProcessorFeature{}
		for _, f47iter := range cr.Spec.ForProvider.ProcessorFeatures {
			f47elem := &svcsdktypes.ProcessorFeature{}
			if f47iter.Name != nil {
				f47elem.Name = f47iter.Name
			}
			if f47iter.Value != nil {
				f47elem.Value = f47iter.Value
			}
			f47 = append(f47, *f47elem)
		}
		res.ProcessorFeatures = f47
	}
	if cr.Spec.ForProvider.PromotionTier != nil {
		promotionTierCopy0 := *cr.Spec.ForProvider.PromotionTier
		if promotionTierCopy0 > math.MaxInt32 || promotionTierCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field PromotionTier is of type int32")
		}
		promotionTierCopy := int32(promotionTierCopy0)
		res.PromotionTier = &promotionTierCopy
	}
	if cr.Spec.ForProvider.PubliclyAccessible != nil {
		res.PubliclyAccessible = cr.Spec.ForProvider.PubliclyAccessible
	}
	if cr.Status.AtProvider.ReplicaMode != nil {
		res.ReplicaMode = svcsdktypes.ReplicaMode(*cr.Status.AtProvider.ReplicaMode)
	}
	if cr.Spec.ForProvider.StorageThroughput != nil {
		storageThroughputCopy0 := *cr.Spec.ForProvider.StorageThroughput
		if storageThroughputCopy0 > math.MaxInt32 || storageThroughputCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field StorageThroughput is of type int32")
		}
		storageThroughputCopy := int32(storageThroughputCopy0)
		res.StorageThroughput = &storageThroughputCopy
	}
	if cr.Spec.ForProvider.StorageType != nil {
		res.StorageType = cr.Spec.ForProvider.StorageType
	}
	if cr.Spec.ForProvider.TagSpecifications != nil {
		f55 := []svcsdktypes.TagSpecification{}
		for _, f55iter := range cr.Spec.ForProvider.TagSpecifications {
			f55elem := &svcsdktypes.TagSpecification{}
			if f55iter.ResourceType != nil {
				f55elem.ResourceType = f55iter.ResourceType
			}
			if f55iter.Tags != nil {
				f55elemf1 := []svcsdktypes.Tag{}
				for _, f55elemf1iter := range f55iter.Tags {
					f55elemf1elem := &svcsdktypes.Tag{}
					if f55elemf1iter.Key != nil {
						f55elemf1elem.Key = f55elemf1iter.Key
					}
					if f55elemf1iter.Value != nil {
						f55elemf1elem.Value = f55elemf1iter.Value
					}
					f55elemf1 = append(f55elemf1, *f55elemf1elem)
				}
				f55elem.Tags = f55elemf1
			}
			f55 = append(f55, *f55elem)
		}
		res.TagSpecifications = f55
	}
	if cr.Spec.ForProvider.TDECredentialARN != nil {
		res.TdeCredentialArn = cr.Spec.ForProvider.TDECredentialARN
	}
	if cr.Spec.ForProvider.TDECredentialPassword != nil {
		res.TdeCredentialPassword = cr.Spec.ForProvider.TDECredentialPassword
	}

	return res, nil
}

// GenerateDeleteDBInstanceInput returns a deletion input.
func GenerateDeleteDBInstanceInput(cr *svcapitypes.DBInstance) (*svcsdk.DeleteDBInstanceInput, error) {
	res := &svcsdk.DeleteDBInstanceInput{}

	return res, nil
}

// IsNotFound returns whether the given error means that the resource does not exist.
func IsNotFound(err error) bool {
	var ae smithy.APIError
	return errors.As(err, &ae) && ae.ErrorCode() == "DBInstanceNotFound"
}
