{{ template "boilerplate" }}

// Code generated by provider-aws-v2 codegen. DO NOT EDIT.

// Package {{ .APIVersion }} is the {{ .APIVersion }} version of the {{ .APIGroup }} API.
// +kubebuilder:object:generate=true
// +groupName={{ .APIGroup }}
// +versionName={{ .APIVersion }}
package {{ .APIVersion }}
