{{ template "boilerplate" }}

// Code generated by provider-aws-v2 codegen. DO NOT EDIT.

package {{ .APIVersion }}

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var _ = &metav1.Time{}
{{ range $typeDef := .TypeDefs }}
{{ template "type_def" $typeDef }}
{{- end }}
